category: application
doc: |
  Application definition for a configuration file of the paraprobe-transcoder tool.
  
  This tool is part of the paraprobe-toolbox. Inspect :ref:`NXapm_paraprobe_tool_config` for details.
# symbols:
#   doc: |
#     The symbols used in the schema to specify e.g. dimensions of arrays.
type: group
# official NeXus appdef headers
NXapm_paraprobe_transcoder_config(NXobject):
  (NXentry):
    exists: [min, 1, max, 1]
    # by default for appdefs the value of the exists keyword is required unless it is explicitly specified differently
    definition(NX_CHAR):
      \@version(NX_CHAR):
      enumeration: [NXapm_paraprobe_transcoder_config]
    # tool-specific
    transcode(NXapm_paraprobe_tool_config):
      exists: [min, 1, max, 1]
      (NXidentifier):
        exists: optional
      analysis_identifier(NX_UINT):
        exists: recommended
      reconstruction(NXserialized):
        type(NX_CHAR):
        path(NX_CHAR):
        checksum(NX_CHAR):
        algorithm(NX_CHAR):
        position(NX_CHAR):
        mass_to_charge(NX_CHAR):
      ranging(NXserialized):
        doc: |
          Specification of the ranging definition file to use for this analysis.
        type(NX_CHAR):
        path(NX_CHAR):
        checksum(NX_CHAR):
        algorithm(NX_CHAR):
      # tool-specific parameter
      # filter
    common(NXapm_paraprobe_tool_common): 
      status(NX_CHAR):
      programID(NXprogram):
        exists: [min, 1, max, infty]
        program(NX_CHAR):
          \@version(NX_CHAR):
      profiling(NXcs_profiling):
        exists: recommended
        start_time(NX_DATE_TIME):
        end_time(NX_DATE_TIME):
        total_elapsed_time(NX_FLOAT):
        current_working_directory(NX_CHAR):
