category: base
doc: |
  Base class documenting the configuration used for a tool of the paraprobe-toolbox.
  
  The paraprobe-toolbox is a collection of open-source software tools for performing
  efficient analyses of point cloud data where each point can represent atoms or
  (molecular) ions. A key application of the toolbox has been for research in the
  field of Atom Probe Tomography (APT) and related Field Ion Microscopy (FIM):
  
  * `paraprobe-toolbox <https://www.gitlab.com/paraprobe/paraprobe-toolbox>`_
  * `M. Kühbach et al. <https://paraprobe-toolbox.readthedocs.io/en/main/>`_
  
  The toolbox does not replace but complements existent software tools in this
  research field. Given its capabilities of handling points as objects with
  properties and enabling analyses of the spatial arrangement of and inter-
  sections between geometric primitives, the software can equally be used
  for analyzing data in Materials Science and Materials Engineering.
  
  The configuration and results of a run of a tool from the toolbox is documented
  using binary container formats. Currently, paraprobe-toolbox uses the
  Hierarchical Data Format 5 (HDF5).
type: group
NXapm_paraprobe_tool_config(NXobject):
  # sequence_id is inherited from NXprocess
  (NXidentifier):
  analysis_identifier(NX_UINT):
    doc: |
      Internal identifier used by the tool to refer to an analysis (aka simulation id).
    unit: NX_UNITLESS
  description(NX_CHAR):
    doc: |
      Possibility for leaving a free-text description about this analysis.
      
      Although offered here for convenience we strongly encourage to
      parameterize such descriptions as much as possible to support
      reusage and clearer communication.
  # tool-specific input, examples for definitions for common types of input granularized into this
  # base class from which tool-specific appdefs inherit
  reconstruction(NXserialized):
    doc: |
      Specification of the tomographic reconstruction to use for this analysis.
      
      Typically, reconstructions in the field of atom probe tomography are communicated
      via files which store at least reconstructed ion positions and mass-to-charge-state-ratio
      values. Container files like HDF5 though can store multiple reconstructions.
      Therefore, the position and mass_to_charge concepts point to specific instances
      to use for this analysis.
    position(NX_CHAR):
      doc: |
        Name of the node which resolves the reconstructed ion position
        values to use for this analysis.
    mass_to_charge(NX_CHAR):
      doc: |
        Name of the node which resolves the mass-to-charge-state-ratio
        values to use for this analysis.
  ranging(NXserialized):
    doc: |
      Specification of the ranging definitions to use for this analysis.
      
      Ranging is the process of labeling time-of-flight data with so-called iontypes
      (aka ion species). Ideally, iontypes specify the most likely (molecular) ion
      that is assumed to have been evaporated given that its mass-to-charge-state ratio
      lies within the specific mass-to-charge-state-ratio value interval of the iontype.
      
      The so-called UNKNOWNTYPE iontype represents the null model of an ion
      that has not been ranged (for whatever reasons).
      The identifier of this special iontype is always the reserved value 0.
    ranging_definitions(NX_CHAR):
      doc: |
        Name of the (parent) node directly below which (in the hierarchy)
        the ranging definition for (molecular) ions are stored.
  surface(NXserialized):
    doc: |
      Specification of the triangulated surface mesh to use for this analysis.
      
      Such a surface mesh can be used to define the edge of the reconstructed
      volume to account for finite size effects.
    # mesh(NX_CHAR):
    #   doc: |
    #     Name of the (parent) node directly below which (in the hierarchy)
    #     an instance of :ref:`NXcg_triangle_set` is stored.
  surface_distance(NXserialized):
    doc: |
      Specification of the point-to-triangulated-surface-mesh distances to
      use for this analysis.
    distance(NX_CHAR):
      doc: |
        Absolute path in the (HDF5) file that points to the distance values.
        The tool assumes that the values are stored in the same order as
        points (ions).
  # filters
  (NXspatial_filter):
  (NXsubsampling_filter):
  (NXmatch_filter):
