category: application
doc: |
  Config for a run with Alaukik Saxena's composition space tool.
  
  This is an initial draft application definition for the common NFDI-MatWerk,
  FAIRmat infrastructure use case IUC09 how to improve the organization and
  results storage of the composition space tool and make these data at the
  same time directly understandable for research data management systems
  like NOMAD Oasis.
symbols:
  doc: |
    The symbols used in the schema to specify e.g. dimensions of arrays.
  n_voxel: |
    Number of voxel of discretized domain for analyzed part of the dataset.
  d: |
    The dimensionality of the grid.
  c: |
    The cardinality or total number of cells/grid points.
  n_clst_dict: |
    Number of terms in the composition clustering dictionary
  n_spat_dict: |
    Number of terms in the position clustering dictionary
type: group
NXapm_compositionspace_config(NXobject):
  # by default for appdefs the value of the exists keyword is required unless it is explicitly specified differently
  (NXentry):
    exists: [min, 1, max, 1]
    definition(NX_CHAR):
      \@version(NX_CHAR):
      enumeration: [NXapm_compositionspace_config]
    config(NXobject):
      (NXidentifier):
        exists: optional
      analysis_identifier(NX_UINT):
        exists: recommended
      reconstruction(NXserialized):
        type(NX_CHAR):
        path(NX_CHAR):
        checksum(NX_CHAR):
        algorithm(NX_CHAR):
        position(NX_CHAR):
        mass_to_charge(NX_CHAR):
      ranging(NXserialized):
        type(NX_CHAR):
        path(NX_CHAR):
        checksum(NX_CHAR):
        algorithm(NX_CHAR):
        ranging_definitions(NX_CHAR):
      edge_length(NX_FLOAT):
        doc: |
          Edge length of the cubic voxels that is used for discretizing the point cloud in the voxelization step.
        unit: NX_LENGTH
      bics_clusters(NX_UINT):
        doc: |
          The maximum number of components configured for the segmentation of the voxel
          set into a mixture of voxels with that many different chemical compositions.
        unit: NX_UNITLESS
      ml_models(NXobject):
        doc: |
          The configuration of the machine learning model used in the segmentation step.
        # name(NX_CHAR):
        #   doc: |
        #     Name of the model to be used.
        gaussian_mixture(NXobject):
          doc: |
             Configuration for the Gaussian mixture model that is used in the segmentation step.
        # random_forest(NXobject):
        #   doc: |
        #     Configuration for the random forest model.
        dbscan(NXobject):
          doc: |
            Configuration for the DBScan algorithm that is used in the clustering step.
          eps(NX_FLOAT):
            doc: |
              The maximum distance between two samples for one to
              be considered as in the neighborhood of the other.
            unit: NX_LENGTH
          min_samples(NX_UINT):
            doc: |
              The number of samples (or total weight) in a neighborhood
              for a point to be considered as a core point.
            unit: NX_UNITLESS
    common(NXobject): 
      status(NX_CHAR):
      programID(NXprogram):
        exists: [min, 1, max, infty]
        program(NX_CHAR):
          \@version(NX_CHAR):
      profiling(NXcs_profiling):
        exists: recommended
        start_time(NX_DATE_TIME):
        end_time(NX_DATE_TIME):
        total_elapsed_time(NX_FLOAT):
        current_working_directory(NX_CHAR):
