category: application
doc: |
  Application definition for a configuration file of the paraprobe-ranger tool.
  
  This tool is part of the paraprobe-toolbox. Inspect :ref:`NXapm_paraprobe_tool_config` for details.
symbols:
  doc: |
    The symbols used in the schema to specify e.g. dimensions of arrays.
  n_nuclids: |
    The number of isotopes to consider as building blocks for searching molecular
    ions.
  n_composition: |
    The number of compositions to consider for molecular ion search tasks.
type: group
NXapm_paraprobe_ranger_config(NXobject):
  (NXentry):
    exists: [min, 1, max, 1]
    definition(NX_CHAR):
      \@version(NX_CHAR):
      enumeration: [NXapm_paraprobe_ranger_config]
    # tool-specific
    range(NXapm_paraprobe_tool_config):
      exists: [min, 1, max, 1]
      (NXidentifier):
        exists: optional
      analysis_identifier(NX_UINT):
        exists: recommended
      reconstruction(NXserialized):
        type(NX_CHAR):
        path(NX_CHAR):
        checksum(NX_CHAR):
        algorithm(NX_CHAR):
        position(NX_CHAR):
        mass_to_charge(NX_CHAR):
      ranging(NXserialized):
        type(NX_CHAR):
        path(NX_CHAR):
        checksum(NX_CHAR):
        algorithm(NX_CHAR):
        ranging_definitions(NX_CHAR):
      # filter
      spatial_filter(NXspatial_filter):
        windowing_method(NX_CHAR):
        hexahedron_set(NXcg_hexahedron_set):
          exists: optional
          dimensionality(NX_POSINT):
          cardinality(NX_POSINT):
          identifier_offset(NX_INT):
          hexahedra(NXcg_face_list_data_structure):
            vertices(NX_UINT):
        cylinder_set(NXcg_cylinder_set):
          exists: optional
          dimensionality(NX_POSINT):
          cardinality(NX_POSINT):
          identifier_offset(NX_INT):
          center(NX_NUMBER):
          height(NX_NUMBER):
          radii(NX_NUMBER):
        ellipsoid_set(NXcg_ellipsoid_set):
          exists: optional
          dimensionality(NX_POSINT):
          cardinality(NX_POSINT):
          identifier_offset(NX_INT):
          center(NX_NUMBER):
          half_axes_radii(NX_NUMBER):
          orientation(NX_NUMBER):
        polyhedron_set(NXcg_polyhedron_set):
          exists: optional
          # TODO
        bitmask(NXcs_filter_boolean_mask):
          exists: optional
          number_of_objects(NX_UINT):
          bitdepth(NX_UINT):
          mask(NX_UINT):
          # leave open if scalar or matrix
          #   dim: (i,)
          identifier(NX_UINT):
      evaporation_id_filter(NXsubsampling_filter):
        exists: optional
        min_incr_max(NX_INT):
      iontype_filter(NXmatch_filter):
        exists: optional
        method(NX_CHAR):
        match(NX_NUMBER):
      hit_multiplicity_filter(NXmatch_filter):
        exists: optional
        method(NX_CHAR):
        match(NX_NUMBER):

      # tool-specific parameter
    # molecular_ion_search(NXapm_paraprobe_tool_config):
      # exists: ['min', '0', 'max', 'unbounded']
      # # extent if needed
      # assumed_composition_isotopes(NX_UINT):
        # exists: optional
        # doc: |
          # A list of pairs of number of protons and either the value 0 (per row)
          # or the mass number for all those isotopes which are assumed present
          # in a virtual specimen.
          # The purpose of this field is to compute also composition-weighted
          # products to yield a simple estimation which could potentially help
          # scientists to judge if certain molecular ions are to be expected.
          # The corresponding setting store_composition_weighted_product should be
          # activated.
        # unit: NX_UNITLESS
        # dim: (n_composition, 2)
      # assumed_composition_value(NX_FLOAT):
        # doc: |
          # A list of atomic (at.-%) ! percent values for the composition of each
          # isotope in the virtual specimen following the sequence of
          # assumed_composition_isotopes.
        # unit: NX_DIMENSIONLESS
        # dim: (n_compositions,)
      # isotope_whitelist(NX_UINT):
        # doc: |
          # A list of pairs of number of protons and mass number for all isotopes
          # to consider that can be composed into (molecular) ions, during the
          # recursive molecular_ion_search.
        # unit: NX_UNITLESS
        # dim: (n_nuclids, 2)
      # mass_to_charge_interval(NX_FLOAT):
        # doc: |
          # The mass-to-charge-state ratio interval in which
          # all molecular ions are searched.
        # unit: NX_ANY  # u
        # dim: (2,)
      # maximum_charge(NX_UINT):
        # doc: |
          # The maximum charge that a molecular ion should have.
        # unit: NX_UNITLESS
      # maximum_number_of_isotopes(NX_UINT):
        # doc: |
          # The maximum number of isotopes of which the molecular ion
          # should be composed. Currently this must not be larger than 32.
          
          # Users should be warned that the larger the maximum_charge and
          # especially the larger the maximum_number_of_isotopes is chosen,
          # the eventually orders of magnitude more costly the search becomes.
          
          # This is because paraprobe-ranger computes really all (at least)
          # theoretically possible combinations that would have likely a
          # mass-to-charge-state ratio in the specified mass_to_charge_interval.
          # It is the challenge in atom probe to judge which of these (molecular)
          # ions are feasible and also practically possible. This tool does not
          # answer this question.
          
          # Namely, which specific molecular ion will evaporate, remain stable
          # during flight and becomes detected is a complicated and in many cases
          # not yet in detail understood phenomenon. The ab-initio conditions
          # before and during launch, the local environment, arrangement and field
          # as well as the flight phase in an evacuated but not analysis chamber
          # with a complex electrical field, eventual laser pulsing in place,
          # temperature and remaining atoms or molecules all can have an effect
          # which iontypes are really physically evaporating and detected.
        # unit: NX_UNITLESS
      # store_atomic_mass_sum(NX_BOOLEAN):
        # doc: |
          # Report the accumulated atomic mass from each isotope building the ion.
          # Accounts for each identified ion. Relatistic effects are not accounted for.
      # store_natural_abundance_product(NX_BOOLEAN):
        # doc: |
          # Report the product of the natural abundances from each isotope building
          # the ion. Accounts for each identified ion.
          
          # The value zero indicates it is not possible to build such molecular ion
          # from nuclids which are all observationally stable.
          # Very small values can give an idea/about how likely such a molecular ion
          # is expected to form assuming equal probabilities.
          
          # However in atom probe experiments this product has to be modified
          # by the (spatially-correlated) local composition in the region from
          # which the ions launch because the formation of a molecular ion depends
          # as summarized under maximum_number_of_isotopes on the specific
          # quantum-mechanical configuration and field state upon launch
          # or/and (early state) of flight respectively.
          # We are aware that this modified product can have a substantially
          # different value than the natural_abundance_product.
          
          # Natural abundancies folded with the estimated compositions of the
          # specimen can differ by orders of magnitude.
        # # add assumed composition of the specimen
      # store_composition_weighted_product(NX_BOOLEAN):
        # doc: |
          # Report the product of the composition from each isotope building the
          # ion. This sets strong constraints on the molecular ions which are
          # expected to have at all a noteworthy product value.
          # It should not be forgotten though the computation relies on assumptions:
          
          # * The composition is homogeneous within the virtual specimen.
          # * It is a priori known which nuclids the specimen is build of.
          
      # store_charge_state(NX_BOOLEAN):
       # doc: |
          # Report the charge state of the ions.
      # store_disjoint_isotopes(NX_BOOLEAN):
        # doc: |
          # Report if identified ions should be characterized wrt to their number of disjoint isotopes.
    # check_existent_ranging(NXapm_paraprobe_tool_config):
      # exists: ['min', '0', 'max', '1']
      # ranging(NXserialized):
        # type(NX_CHAR):
        # path(NX_CHAR):
        # checksum(NX_CHAR):
        # algorithm(NX_CHAR):
        # ranging_definitions(NX_CHAR):
    common(NXapm_paraprobe_tool_common): 
      status(NX_CHAR):
      programID(NXprogram):
        exists: [min, 1, max, infty]
        program(NX_CHAR):
          \@version(NX_CHAR):
      profiling(NXcs_profiling):
        exists: recommended
        start_time(NX_DATE_TIME):
        end_time(NX_DATE_TIME):
        total_elapsed_time(NX_FLOAT):
        current_working_directory(NX_CHAR):
