#!/bin/bash

dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R18_60075-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/FWHM-range.rrng" --output=debug.aus_sydney_bilal_0.nxs 1>stdout.debug.aus_sydney_bilal_0.txt 2>stderr.debug.aus_sydney_bilal_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R04_23087-v02.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R4_23087.RRNG" --output=debug.aus_sydney_breen_0.nxs 1>stdout.debug.aus_sydney_breen_0.txt 2>stderr.debug.aus_sydney_breen_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R18_53705-v03.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R18_53705-v03.rng" --output=debug.aus_sydney_breen_1.nxs 1>stdout.debug.aus_sydney_breen_1.txt 2>stderr.debug.aus_sydney_breen_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R18_55377-v02.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R18_55377-v02.rng" --output=debug.aus_sydney_breen_2.nxs 1>stdout.debug.aus_sydney_breen_2.txt 2>stderr.debug.aus_sydney_breen_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R18_58152-v02.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R18_58152-v02.RRNG" --output=debug.aus_sydney_breen_3.nxs 1>stdout.debug.aus_sydney_breen_3.txt 2>stderr.debug.aus_sydney_breen_3.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R18_59377-v01.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R18_59377.rng" --output=debug.aus_sydney_breen_4.nxs 1>stdout.debug.aus_sydney_breen_4.txt 2>stderr.debug.aus_sydney_breen_4.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R18_60310-v02.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R18_60310-v02.rng" --output=debug.aus_sydney_breen_5.nxs 1>stdout.debug.aus_sydney_breen_5.txt 2>stderr.debug.aus_sydney_breen_5.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/DN5.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/DN5.rrng" --output=debug.aus_sydney_cairney_0.nxs 1>stdout.debug.aus_sydney_cairney_0.txt 2>stderr.debug.aus_sydney_cairney_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/A718 GB R04_11350-V01.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R04_11350-v01.rng.fig.txt" --output=debug.aus_sydney_felfer_0.nxs 1>stdout.debug.aus_sydney_felfer_0.txt 2>stderr.debug.aus_sydney_felfer_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Al-Cu-Sn.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Al-Cu-Sn.rng" --output=debug.aus_sydney_fontaine_alcusn_0.nxs 1>stdout.debug.aus_sydney_fontaine_alcusn_0.txt 2>stderr.debug.aus_sydney_fontaine_alcusn_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Human-tooth-enamel-A.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Human-tooth-enamel.rrng" --output=debug.aus_sydney_fontaine_tooth_0.nxs 1>stdout.debug.aus_sydney_fontaine_tooth_0.txt 2>stderr.debug.aus_sydney_fontaine_tooth_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Human-tooth-enamel-B.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Human-tooth-enamel.rrng" --output=debug.aus_sydney_fontaine_tooth_1.nxs 1>stdout.debug.aus_sydney_fontaine_tooth_1.txt 2>stderr.debug.aus_sydney_fontaine_tooth_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Ranging.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/A.rrng" --output=debug.aus_sydney_lafontaine_0.nxs 1>stdout.debug.aus_sydney_lafontaine_0.txt 2>stderr.debug.aus_sydney_lafontaine_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Ranging.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/B.rrng" --output=debug.aus_sydney_lafontaine_1.nxs 1>stdout.debug.aus_sydney_lafontaine_1.txt 2>stderr.debug.aus_sydney_lafontaine_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Ranging.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/C.rrng" --output=debug.aus_sydney_lafontaine_2.nxs 1>stdout.debug.aus_sydney_lafontaine_2.txt 2>stderr.debug.aus_sydney_lafontaine_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Ranging.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/D.rrng" --output=debug.aus_sydney_lafontaine_3.nxs 1>stdout.debug.aus_sydney_lafontaine_3.txt 2>stderr.debug.aus_sydney_lafontaine_3.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Ranging.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/E.rrng" --output=debug.aus_sydney_lafontaine_4.nxs 1>stdout.debug.aus_sydney_lafontaine_4.txt 2>stderr.debug.aus_sydney_lafontaine_4.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Ranging.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/F.rrng" --output=debug.aus_sydney_lafontaine_5.nxs 1>stdout.debug.aus_sydney_lafontaine_5.txt 2>stderr.debug.aus_sydney_lafontaine_5.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Ranging.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/H.rrng" --output=debug.aus_sydney_lafontaine_6.nxs 1>stdout.debug.aus_sydney_lafontaine_6.txt 2>stderr.debug.aus_sydney_lafontaine_6.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Ranging.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/I.rrng" --output=debug.aus_sydney_lafontaine_7.nxs 1>stdout.debug.aus_sydney_lafontaine_7.txt 2>stderr.debug.aus_sydney_lafontaine_7.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Ranging.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/G- Peak Ranges.rrng" --output=debug.aus_sydney_lafontaine_8.nxs 1>stdout.debug.aus_sydney_lafontaine_8.txt 2>stderr.debug.aus_sydney_lafontaine_8.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-C.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-C.rrng" --output=debug.aus_sydney_lafontaine_9.nxs 1>stdout.debug.aus_sydney_lafontaine_9.txt 2>stderr.debug.aus_sydney_lafontaine_9.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-H.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-H.rrng" --output=debug.aus_sydney_lafontaine_10.nxs 1>stdout.debug.aus_sydney_lafontaine_10.txt 2>stderr.debug.aus_sydney_lafontaine_10.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-A_1.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-A_1.RNG" --output=debug.aus_sydney_lafontaine_11.nxs 1>stdout.debug.aus_sydney_lafontaine_11.txt 2>stderr.debug.aus_sydney_lafontaine_11.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-B_1.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/81-B_1.rrng" --output=debug.aus_sydney_lafontaine_12.nxs 1>stdout.debug.aus_sydney_lafontaine_12.txt 2>stderr.debug.aus_sydney_lafontaine_12.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-B_2.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-B_2.rrng" --output=debug.aus_sydney_lafontaine_13.nxs 1>stdout.debug.aus_sydney_lafontaine_13.txt 2>stderr.debug.aus_sydney_lafontaine_13.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87D_1.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87D_1.rng" --output=debug.aus_sydney_lafontaine_14.nxs 1>stdout.debug.aus_sydney_lafontaine_14.txt 2>stderr.debug.aus_sydney_lafontaine_14.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87D_2.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87D_2.rrng" --output=debug.aus_sydney_lafontaine_15.nxs 1>stdout.debug.aus_sydney_lafontaine_15.txt 2>stderr.debug.aus_sydney_lafontaine_15.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87D_3.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87D_3.rrng" --output=debug.aus_sydney_lafontaine_16.nxs 1>stdout.debug.aus_sydney_lafontaine_16.txt 2>stderr.debug.aus_sydney_lafontaine_16.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-E_1.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-E_1.rrng" --output=debug.aus_sydney_lafontaine_17.nxs 1>stdout.debug.aus_sydney_lafontaine_17.txt 2>stderr.debug.aus_sydney_lafontaine_17.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-E_2.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-E_2.rrng" --output=debug.aus_sydney_lafontaine_18.nxs 1>stdout.debug.aus_sydney_lafontaine_18.txt 2>stderr.debug.aus_sydney_lafontaine_18.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-F-1.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-F.rrng" --output=debug.aus_sydney_lafontaine_19.nxs 1>stdout.debug.aus_sydney_lafontaine_19.txt 2>stderr.debug.aus_sydney_lafontaine_19.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-F_2.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-F.rrng" --output=debug.aus_sydney_lafontaine_20.nxs 1>stdout.debug.aus_sydney_lafontaine_20.txt 2>stderr.debug.aus_sydney_lafontaine_20.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-G_1.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-G_1 Peak Ranges.rrng" --output=debug.aus_sydney_lafontaine_21.nxs 1>stdout.debug.aus_sydney_lafontaine_21.txt 2>stderr.debug.aus_sydney_lafontaine_21.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-G_2.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-G_2 Peak Ranges.rrng" --output=debug.aus_sydney_lafontaine_22.nxs 1>stdout.debug.aus_sydney_lafontaine_22.txt 2>stderr.debug.aus_sydney_lafontaine_22.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-I-1.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-I-1.rrng" --output=debug.aus_sydney_lafontaine_23.nxs 1>stdout.debug.aus_sydney_lafontaine_23.txt 2>stderr.debug.aus_sydney_lafontaine_23.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-I-2.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-I-2.rrng" --output=debug.aus_sydney_lafontaine_24.nxs 1>stdout.debug.aus_sydney_lafontaine_24.txt 2>stderr.debug.aus_sydney_lafontaine_24.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-A'.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-A'.rrng" --output=debug.aus_sydney_lafontaine_25.nxs 1>stdout.debug.aus_sydney_lafontaine_25.txt 2>stderr.debug.aus_sydney_lafontaine_25.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-B'.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-B'.rrng" --output=debug.aus_sydney_lafontaine_26.nxs 1>stdout.debug.aus_sydney_lafontaine_26.txt 2>stderr.debug.aus_sydney_lafontaine_26.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-E'.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-E'.rng" --output=debug.aus_sydney_lafontaine_27.nxs 1>stdout.debug.aus_sydney_lafontaine_27.txt 2>stderr.debug.aus_sydney_lafontaine_27.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-F'.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-F'.RNG" --output=debug.aus_sydney_lafontaine_28.nxs 1>stdout.debug.aus_sydney_lafontaine_28.txt 2>stderr.debug.aus_sydney_lafontaine_28.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-G'.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-G'-Peak Ranges.rrng" --output=debug.aus_sydney_lafontaine_29.nxs 1>stdout.debug.aus_sydney_lafontaine_29.txt 2>stderr.debug.aus_sydney_lafontaine_29.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-E'.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-E'.rrng" --output=debug.aus_sydney_lafontaine_30.nxs 1>stdout.debug.aus_sydney_lafontaine_30.txt 2>stderr.debug.aus_sydney_lafontaine_30.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-F'.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-F'.rrng" --output=debug.aus_sydney_lafontaine_31.nxs 1>stdout.debug.aus_sydney_lafontaine_31.txt 2>stderr.debug.aus_sydney_lafontaine_31.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-H'.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-H'.rrng" --output=debug.aus_sydney_lafontaine_32.nxs 1>stdout.debug.aus_sydney_lafontaine_32.txt 2>stderr.debug.aus_sydney_lafontaine_32.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R87-I'.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/87-I'.rrng" --output=debug.aus_sydney_lafontaine_33.nxs 1>stdout.debug.aus_sydney_lafontaine_33.txt 2>stderr.debug.aus_sydney_lafontaine_33.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R04_22071.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R04_22071.RRNG" --output=debug.aus_sydney_rielli_primig_0.nxs 1>stdout.debug.aus_sydney_rielli_primig_0.txt 2>stderr.debug.aus_sydney_rielli_primig_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R21_08680-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R21_08680.rrng" --output=debug.aut_leoben_leitner_0.nxs 1>stdout.debug.aut_leoben_leitner_0.txt 2>stderr.debug.aut_leoben_leitner_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R21_07575-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R21_07575-v02.rrng" --output=debug.aut_leoben_mendez_martin_0.nxs 1>stdout.debug.aut_leoben_mendez_martin_0.txt 2>stderr.debug.aut_leoben_mendez_martin_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/finfet_system.ato" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/finfet.rrng" --output=debug.bel_leuven_imec_0.nxs 1>stdout.debug.bel_leuven_imec_0.txt 2>stderr.debug.bel_leuven_imec_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/multilayer_system.ato" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/multilayer.rrng" --output=debug.bel_leuven_imec_1.nxs 1>stdout.debug.bel_leuven_imec_1.txt 2>stderr.debug.bel_leuven_imec_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R47_00667-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/RRNG-FeMnC.RRNG" --output=debug.can_hamilton_morisset_0.nxs 1>stdout.debug.can_hamilton_morisset_0.txt 2>stderr.debug.can_hamilton_morisset_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_26731-v03.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_26731.rrng" --output=debug.gbr_oxford_chen_0.nxs 1>stdout.debug.gbr_oxford_chen_0.txt 2>stderr.debug.gbr_oxford_chen_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_25438-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_25438.rrng" --output=debug.gbr_oxford_chen_1.nxs 1>stdout.debug.gbr_oxford_chen_1.txt 2>stderr.debug.gbr_oxford_chen_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_26717-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_26717.rrng" --output=debug.gbr_oxford_chen_2.nxs 1>stdout.debug.gbr_oxford_chen_2.txt 2>stderr.debug.gbr_oxford_chen_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_25556-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_25556.rrng" --output=debug.gbr_oxford_chen_3.nxs 1>stdout.debug.gbr_oxford_chen_3.txt 2>stderr.debug.gbr_oxford_chen_3.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R34_05028-v07.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R34_05028-v07.rrng" --output=debug.gbr_oxford_chen_4.nxs 1>stdout.debug.gbr_oxford_chen_4.txt 2>stderr.debug.gbr_oxford_chen_4.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_25977-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_25977.rrng" --output=debug.gbr_oxford_chen_5.nxs 1>stdout.debug.gbr_oxford_chen_5.txt 2>stderr.debug.gbr_oxford_chen_5.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R34_05025-v04.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R34_05025.rrng" --output=debug.gbr_oxford_chen_6.nxs 1>stdout.debug.gbr_oxford_chen_6.txt 2>stderr.debug.gbr_oxford_chen_6.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_26702-v03.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_26702.rrng" --output=debug.gbr_oxford_chen_7.nxs 1>stdout.debug.gbr_oxford_chen_7.txt 2>stderr.debug.gbr_oxford_chen_7.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_26697-v03.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_26697.rrng" --output=debug.gbr_oxford_chen_8.nxs 1>stdout.debug.gbr_oxford_chen_8.txt 2>stderr.debug.gbr_oxford_chen_8.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_25949-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_25949.rrng" --output=debug.gbr_oxford_chen_9.nxs 1>stdout.debug.gbr_oxford_chen_9.txt 2>stderr.debug.gbr_oxford_chen_9.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_09806-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_09806-v02.rrng" --output=debug.gbr_oxford_davis_193.nxs 1>stdout.debug.gbr_oxford_davis_193.txt 2>stderr.debug.gbr_oxford_davis_193.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_09837-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_09837-v01.rrng" --output=debug.gbr_oxford_davis_285.nxs 1>stdout.debug.gbr_oxford_davis_285.txt 2>stderr.debug.gbr_oxford_davis_285.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_22266-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_22266.RRNG" --output=debug.gbr_oxford_dffit_0.nxs 1>stdout.debug.gbr_oxford_dffit_0.txt 2>stderr.debug.gbr_oxford_dffit_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_17798-v01-crop.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_17798-v01.RRNG" --output=debug.gbr_oxford_dffit_1.nxs 1>stdout.debug.gbr_oxford_dffit_1.txt 2>stderr.debug.gbr_oxford_dffit_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_24453-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_24436_R14_24453.rrng" --output=debug.gbr_oxford_gascell_0.nxs 1>stdout.debug.gbr_oxford_gascell_0.txt 2>stderr.debug.gbr_oxford_gascell_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_24546-v12.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_24546_Mg880Ge_PostO2.rrng" --output=debug.gbr_oxford_gascell_1.nxs 1>stdout.debug.gbr_oxford_gascell_1.txt 2>stderr.debug.gbr_oxford_gascell_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_24902-v07.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_24902-v07_PostH2O.rrng" --output=debug.gbr_oxford_gascell_2.nxs 1>stdout.debug.gbr_oxford_gascell_2.txt 2>stderr.debug.gbr_oxford_gascell_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_26444-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_26444-v01.RRNG" --output=debug.gbr_oxford_gascell_7.nxs 1>stdout.debug.gbr_oxford_gascell_7.txt 2>stderr.debug.gbr_oxford_gascell_7.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_26445-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_26445-v01.rrng" --output=debug.gbr_oxford_gascell_8.nxs 1>stdout.debug.gbr_oxford_gascell_8.txt 2>stderr.debug.gbr_oxford_gascell_8.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R34_05028-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R34_05028-v02.rrng" --output=debug.gbr_oxford_haley_1.nxs 1>stdout.debug.gbr_oxford_haley_1.txt 2>stderr.debug.gbr_oxford_haley_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_21676-v04.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_21676 range.rrng" --output=debug.gbr_oxford_haley_2.nxs 1>stdout.debug.gbr_oxford_haley_2.txt 2>stderr.debug.gbr_oxford_haley_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R34_05068-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R34_05068.rrng" --output=debug.gbr_oxford_haley_3.nxs 1>stdout.debug.gbr_oxford_haley_3.txt 2>stderr.debug.gbr_oxford_haley_3.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_19943-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R14_19943.rrng" --output=debug.gbr_oxford_haley_4.nxs 1>stdout.debug.gbr_oxford_haley_4.txt 2>stderr.debug.gbr_oxford_haley_4.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_07490-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_07490-v02.cluster.rrng" --output=debug.gbr_oxford_jenkins_0.nxs 1>stdout.debug.gbr_oxford_jenkins_0.txt 2>stderr.debug.gbr_oxford_jenkins_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/23314.POS" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5083_23314_MJ_decomp_Dcopy_YS.RRNG" --output=debug.gbr_oxford_shi_0.nxs 1>stdout.debug.gbr_oxford_shi_0.txt 2>stderr.debug.gbr_oxford_shi_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R68_06299-v05.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/MgGdZn.rrng" --output=debug.ger_aachen_mouhib_0.nxs 1>stdout.debug.ger_aachen_mouhib_0.txt 2>stderr.debug.ger_aachen_mouhib_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R68_06337-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/MgGdZn.rrng" --output=debug.ger_aachen_mouhib_1.nxs 1>stdout.debug.ger_aachen_mouhib_1.txt 2>stderr.debug.ger_aachen_mouhib_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R68_06796-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/MgGdZn.rrng" --output=debug.ger_aachen_mouhib_2.nxs 1>stdout.debug.ger_aachen_mouhib_2.txt 2>stderr.debug.ger_aachen_mouhib_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R68_06994-v04.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/MgGd.RRNG" --output=debug.ger_aachen_mouhib_3.nxs 1>stdout.debug.ger_aachen_mouhib_3.txt 2>stderr.debug.ger_aachen_mouhib_3.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_plan-view_600C.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_plan-view_600C.rrng" --output=debug.ger_aachen_saelker_0.nxs 1>stdout.debug.ger_aachen_saelker_0.txt 2>stderr.debug.ger_aachen_saelker_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_flake_900C.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_flake_900C.rrng" --output=debug.ger_aachen_saelker_1.nxs 1>stdout.debug.ger_aachen_saelker_1.txt 2>stderr.debug.ger_aachen_saelker_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_plan-view_700C.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_plan-view_700C.rrng" --output=debug.ger_aachen_saelker_2.nxs 1>stdout.debug.ger_aachen_saelker_2.txt 2>stderr.debug.ger_aachen_saelker_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_plan-view_asdep.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_plan-view_asdep.rrng" --output=debug.ger_aachen_saelker_3.nxs 1>stdout.debug.ger_aachen_saelker_3.txt 2>stderr.debug.ger_aachen_saelker_3.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/TiAlN_film_cross-section_1200C.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/TiAlN_film_cross-section_1200C.rrng" --output=debug.ger_aachen_saelker_4.nxs 1>stdout.debug.ger_aachen_saelker_4.txt 2>stderr.debug.ger_aachen_saelker_4.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_cross-section_800C.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_cross-section_800C.rrng" --output=debug.ger_aachen_saelker_5.nxs 1>stdout.debug.ger_aachen_saelker_5.txt 2>stderr.debug.ger_aachen_saelker_5.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_flake_1100C.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_flake_1100C.rrng" --output=debug.ger_aachen_saelker_6.nxs 1>stdout.debug.ger_aachen_saelker_6.txt 2>stderr.debug.ger_aachen_saelker_6.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/TiAlN_film_cross-section_850C.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/TiAlN_film_cross-section_850C.rrng" --output=debug.ger_aachen_saelker_7.nxs 1>stdout.debug.ger_aachen_saelker_7.txt 2>stderr.debug.ger_aachen_saelker_7.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_plan-view_800C.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_plan-view_800C.rrng" --output=debug.ger_aachen_saelker_8.nxs 1>stdout.debug.ger_aachen_saelker_8.txt 2>stderr.debug.ger_aachen_saelker_8.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_cross-section_600C.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_cross-section_600C.rrng" --output=debug.ger_aachen_saelker_9.nxs 1>stdout.debug.ger_aachen_saelker_9.txt 2>stderr.debug.ger_aachen_saelker_9.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/TiAlN_film_cross-section_asdep.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/TiAlN_film_cross-section_asdep.rrng" --output=debug.ger_aachen_saelker_10.nxs 1>stdout.debug.ger_aachen_saelker_10.txt 2>stderr.debug.ger_aachen_saelker_10.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_cross-section_900C.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_cross-section_900C.rrng" --output=debug.ger_aachen_saelker_11.nxs 1>stdout.debug.ger_aachen_saelker_11.txt 2>stderr.debug.ger_aachen_saelker_11.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_cross-section_asdep.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_cross-section_asdep.rrng" --output=debug.ger_aachen_saelker_12.nxs 1>stdout.debug.ger_aachen_saelker_12.txt 2>stderr.debug.ger_aachen_saelker_12.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_cross-section_700C.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_cross-section_700C.rrng" --output=debug.ger_aachen_saelker_13.nxs 1>stdout.debug.ger_aachen_saelker_13.txt 2>stderr.debug.ger_aachen_saelker_13.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_flake_asdep.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_flake_asdep.rrng" --output=debug.ger_aachen_saelker_14.nxs 1>stdout.debug.ger_aachen_saelker_14.txt 2>stderr.debug.ger_aachen_saelker_14.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_cross-section_1000C.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/VAlN_film_cross-section_1000C.rrng" --output=debug.ger_aachen_saelker_15.nxs 1>stdout.debug.ger_aachen_saelker_15.txt 2>stderr.debug.ger_aachen_saelker_15.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/8fc2f3c8-213d-46d6-84da-255cb3dee017.apt" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R68_06755 Top Level ROI.RRNG" --output=debug.ger_aachen_seehaus_0.nxs 1>stdout.debug.ger_aachen_seehaus_0.txt 2>stderr.debug.ger_aachen_seehaus_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/d3ecc995-071d-4374-be52-3d489b5a0f6a.apt" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R68_07086 Top Level ROI.RRNG" --output=debug.ger_aachen_seehaus_1.nxs 1>stdout.debug.ger_aachen_seehaus_1.txt 2>stderr.debug.ger_aachen_seehaus_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5006_29110_Top_Level_ROI.apt" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5006_29110_Top_Level_ROI.RRNG" --output=debug.ger_duesseldorf_antonov_0.nxs 1>stdout.debug.ger_duesseldorf_antonov_0.txt 2>stderr.debug.ger_duesseldorf_antonov_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R87_02935-v03.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R87_02935-v03.rrng" --output=debug.ger_duesseldorf_antonov_1.nxs 1>stdout.debug.ger_duesseldorf_antonov_1.txt 2>stderr.debug.ger_duesseldorf_antonov_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76_27632-v07.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76_27632-v07.rrng" --output=debug.ger_duesseldorf_bajaj_0.nxs 1>stdout.debug.ger_duesseldorf_bajaj_0.txt 2>stderr.debug.ger_duesseldorf_bajaj_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76_30139-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76_30139-v02.rrng" --output=debug.ger_duesseldorf_bajaj_1.nxs 1>stdout.debug.ger_duesseldorf_bajaj_1.txt 2>stderr.debug.ger_duesseldorf_bajaj_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76_33455-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76_33455-v01.rrng" --output=debug.ger_duesseldorf_bajaj_2.nxs 1>stdout.debug.ger_duesseldorf_bajaj_2.txt 2>stderr.debug.ger_duesseldorf_bajaj_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R96_33145-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R96_33145-v01.rrng" --output=debug.ger_duesseldorf_balachandran_0.nxs 1>stdout.debug.ger_duesseldorf_balachandran_0.txt 2>stderr.debug.ger_duesseldorf_balachandran_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5076_33297-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5076_33297-v01.rrng" --output=debug.ger_duesseldorf_balachandran_1.nxs 1>stdout.debug.ger_duesseldorf_balachandran_1.txt 2>stderr.debug.ger_duesseldorf_balachandran_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5076_33303-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5076_33303-v01.rrng" --output=debug.ger_duesseldorf_balachandran_2.nxs 1>stdout.debug.ger_duesseldorf_balachandran_2.txt 2>stderr.debug.ger_duesseldorf_balachandran_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5096_35459-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/range_file_RNG.RNG" --output=debug.ger_duesseldorf_balachandran_3.nxs 1>stdout.debug.ger_duesseldorf_balachandran_3.txt 2>stderr.debug.ger_duesseldorf_balachandran_3.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06656-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06656-v02.rrng" --output=debug.ger_duesseldorf_cautaerts_25.nxs 1>stdout.debug.ger_duesseldorf_cautaerts_25.txt 2>stderr.debug.ger_duesseldorf_cautaerts_25.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06656-v03.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06656-v03.rrng" --output=debug.ger_duesseldorf_cautaerts_27.nxs 1>stdout.debug.ger_duesseldorf_cautaerts_27.txt 2>stderr.debug.ger_duesseldorf_cautaerts_27.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R56_02293-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/rng_R56_02293-v01.rng" --output=debug.ger_duesseldorf_cautaerts_58.nxs 1>stdout.debug.ger_duesseldorf_cautaerts_58.txt 2>stderr.debug.ger_duesseldorf_cautaerts_58.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R21_10355-cluster.cluster.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R21_10355-cluster.cluster.rrng" --output=debug.ger_duesseldorf_cautaerts_95.nxs 1>stdout.debug.ger_duesseldorf_cautaerts_95.txt 2>stderr.debug.ger_duesseldorf_cautaerts_95.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R21_10355-v02.cluster.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R21_10355-v02.cluster.rrng" --output=debug.ger_duesseldorf_cautaerts_106.nxs 1>stdout.debug.ger_duesseldorf_cautaerts_106.txt 2>stderr.debug.ger_duesseldorf_cautaerts_106.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06667-v03.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/rangeOptimized.rrng" --output=debug.ger_duesseldorf_cautaerts_289.nxs 1>stdout.debug.ger_duesseldorf_cautaerts_289.txt 2>stderr.debug.ger_duesseldorf_cautaerts_289.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06667-v06.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06667-v06.rng" --output=debug.ger_duesseldorf_cautaerts_305.nxs 1>stdout.debug.ger_duesseldorf_cautaerts_305.txt 2>stderr.debug.ger_duesseldorf_cautaerts_305.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06696-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06696-v01.rrng" --output=debug.ger_duesseldorf_cautaerts_371.nxs 1>stdout.debug.ger_duesseldorf_cautaerts_371.txt 2>stderr.debug.ger_duesseldorf_cautaerts_371.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06697-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06697-v01.rrng" --output=debug.ger_duesseldorf_cautaerts_396.nxs 1>stdout.debug.ger_duesseldorf_cautaerts_396.txt 2>stderr.debug.ger_duesseldorf_cautaerts_396.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06703-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06703-v01.rrng" --output=debug.ger_duesseldorf_cautaerts_462.nxs 1>stdout.debug.ger_duesseldorf_cautaerts_462.txt 2>stderr.debug.ger_duesseldorf_cautaerts_462.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06703-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06703-v02.rrng" --output=debug.ger_duesseldorf_cautaerts_472.nxs 1>stdout.debug.ger_duesseldorf_cautaerts_472.txt 2>stderr.debug.ger_duesseldorf_cautaerts_472.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06703-v03.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R33_06703-v03.rrng" --output=debug.ger_duesseldorf_cautaerts_477.nxs 1>stdout.debug.ger_duesseldorf_cautaerts_477.txt 2>stderr.debug.ger_duesseldorf_cautaerts_477.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R18_15386-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/allicumgag.rrng" --output=debug.ger_duesseldorf_gault_0.nxs 1>stdout.debug.ger_duesseldorf_gault_0.txt 2>stderr.debug.ger_duesseldorf_gault_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76_21659-v01.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76_21659-v01.rng" --output=debug.ger_duesseldorf_kwiatkowski_0.nxs 1>stdout.debug.ger_duesseldorf_kwiatkowski_0.txt 2>stderr.debug.ger_duesseldorf_kwiatkowski_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Annealed CoCrNi_100.csv" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Annealing_M2C_100.RRNG" --output=debug.ger_duesseldorf_li_0.nxs 1>stdout.debug.ger_duesseldorf_li_0.txt 2>stderr.debug.ger_duesseldorf_li_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Annealed CoCrNi_111.csv" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Annealing_M2C_111.RRNG" --output=debug.ger_duesseldorf_li_1.nxs 1>stdout.debug.ger_duesseldorf_li_1.txt 2>stderr.debug.ger_duesseldorf_li_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Annealed_CoCrNi_111_random_dataset.csv" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Annealing_M2C_111.RRNG" --output=debug.ger_duesseldorf_li_2.nxs 1>stdout.debug.ger_duesseldorf_li_2.txt 2>stderr.debug.ger_duesseldorf_li_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Annealed_CoCrNi_100_random_dataset.csv" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Annealing_M2C_100.RRNG" --output=debug.ger_duesseldorf_li_3.nxs 1>stdout.debug.ger_duesseldorf_li_3.txt 2>stderr.debug.ger_duesseldorf_li_3.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5096_37592-v05.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/37592.rrng" --output=debug.ger_duesseldorf_mayweg_0.nxs 1>stdout.debug.ger_duesseldorf_mayweg_0.txt 2>stderr.debug.ger_duesseldorf_mayweg_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5096_41455-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5096_41455-v02.rrng" --output=debug.ger_duesseldorf_mayweg_1.nxs 1>stdout.debug.ger_duesseldorf_mayweg_1.txt 2>stderr.debug.ger_duesseldorf_mayweg_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5096_41894-v05.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5096_41894-v05.rrng" --output=debug.ger_duesseldorf_mayweg_2.nxs 1>stdout.debug.ger_duesseldorf_mayweg_2.txt 2>stderr.debug.ger_duesseldorf_mayweg_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5096_42390-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5096_42390-v02.RNG" --output=debug.ger_duesseldorf_mayweg_3.nxs 1>stdout.debug.ger_duesseldorf_mayweg_3.txt 2>stderr.debug.ger_duesseldorf_mayweg_3.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/D1_High_Hc_R5076_52126.apt" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/D1_High_Hc_R5076_52126.RRNG" --output=debug.ger_duesseldorf_polin_0.nxs 1>stdout.debug.ger_duesseldorf_polin_0.txt 2>stderr.debug.ger_duesseldorf_polin_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/ed47f8ee-c770-4289-8a10-c24f70229d88.POS" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5096_52749_recent_range_file_1.RRNG" --output=debug.ger_duesseldorf_saksena_2.nxs 1>stdout.debug.ger_duesseldorf_saksena_2.txt 2>stderr.debug.ger_duesseldorf_saksena_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76_20169-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76_20169-v01.rrng" --output=debug.ger_duesseldorf_stephenson_0.nxs 1>stdout.debug.ger_duesseldorf_stephenson_0.txt 2>stderr.debug.ger_duesseldorf_stephenson_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5076_36088-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5076_36088-v01.rrng" --output=debug.ger_duesseldorf_zhao_0.nxs 1>stdout.debug.ger_duesseldorf_zhao_0.txt 2>stderr.debug.ger_duesseldorf_zhao_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76_24909-0.5h.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76_24909-0.5h.rng" --output=debug.ger_duesseldorf_zhao_8.nxs 1>stdout.debug.ger_duesseldorf_zhao_8.txt 2>stderr.debug.ger_duesseldorf_zhao_8.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76-26865-PA.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76-26865-PA.RNG" --output=debug.ger_duesseldorf_zhao_9.nxs 1>stdout.debug.ger_duesseldorf_zhao_9.txt 2>stderr.debug.ger_duesseldorf_zhao_9.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76-26737-PA.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76-26737-PA.RNG" --output=debug.ger_duesseldorf_zhao_10.nxs 1>stdout.debug.ger_duesseldorf_zhao_10.txt 2>stderr.debug.ger_duesseldorf_zhao_10.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76-26120-OA.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76-26120-OA.RNG" --output=debug.ger_duesseldorf_zhao_11.nxs 1>stdout.debug.ger_duesseldorf_zhao_11.txt 2>stderr.debug.ger_duesseldorf_zhao_11.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76-26110-30min.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76-26110-0.5h.RNG" --output=debug.ger_duesseldorf_zhao_12.nxs 1>stdout.debug.ger_duesseldorf_zhao_12.txt 2>stderr.debug.ger_duesseldorf_zhao_12.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76-25946-2h.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76-25946-2h.RNG" --output=debug.ger_duesseldorf_zhao_13.nxs 1>stdout.debug.ger_duesseldorf_zhao_13.txt 2>stderr.debug.ger_duesseldorf_zhao_13.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76-25139-2h.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76-25139-2h.RNG" --output=debug.ger_duesseldorf_zhao_14.nxs 1>stdout.debug.ger_duesseldorf_zhao_14.txt 2>stderr.debug.ger_duesseldorf_zhao_14.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76-24909-30min.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R76-24909-30min.rng" --output=debug.ger_duesseldorf_zhao_15.nxs 1>stdout.debug.ger_duesseldorf_zhao_15.txt 2>stderr.debug.ger_duesseldorf_zhao_15.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R25_33096-v02.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R25_33096-v02.rrng" --output=debug.ger_duesseldorf_zhao_16.nxs 1>stdout.debug.ger_duesseldorf_zhao_16.txt 2>stderr.debug.ger_duesseldorf_zhao_16.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/AluminiumNEW.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/AluminiumNEW_MassSpec_ranged.fig.txt" --output=debug.ger_erlangen_felfer_0.nxs 1>stdout.debug.ger_erlangen_felfer_0.txt 2>stderr.debug.ger_erlangen_felfer_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Superalloy.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Superalloy_MassSpec_ranged.fig.txt" --output=debug.ger_erlangen_felfer_1.nxs 1>stdout.debug.ger_erlangen_felfer_1.txt 2>stderr.debug.ger_erlangen_felfer_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R56_01769-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R56_01769.rng.fig.txt" --output=debug.ger_erlangen_felfer_2.nxs 1>stdout.debug.ger_erlangen_felfer_2.txt 2>stderr.debug.ger_erlangen_felfer_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R21_08680-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R21_08680.rrng" --output=debug.ger_erlangen_heller_0.nxs 1>stdout.debug.ger_erlangen_heller_0.txt 2>stderr.debug.ger_erlangen_heller_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R56_03446-v01.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/3446_AP06.RRNG" --output=debug.ger_erlangen_heller_1.nxs 1>stdout.debug.ger_erlangen_heller_1.txt 2>stderr.debug.ger_erlangen_heller_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/1748_Al.h5" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/1748_Al_range_.h5" --output=debug.ger_erlangen_monajem_0.nxs 1>stdout.debug.ger_erlangen_monajem_0.txt 2>stderr.debug.ger_erlangen_monajem_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R52_05169-v04.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/range_file.rrng" --output=debug.ger_karlsruhe_pantenburg_3.nxs 1>stdout.debug.ger_karlsruhe_pantenburg_3.txt 2>stderr.debug.ger_karlsruhe_pantenburg_3.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R36_03240-v01.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R36_03240-v01.rng" --output=debug.ger_saarbruecken_pauly_0.nxs 1>stdout.debug.ger_saarbruecken_pauly_0.txt 2>stderr.debug.ger_saarbruecken_pauly_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R36_03244-v01.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R36_03244-v01.rng" --output=debug.ger_saarbruecken_pauly_1.nxs 1>stdout.debug.ger_saarbruecken_pauly_1.txt 2>stderr.debug.ger_saarbruecken_pauly_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/060720a-1.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/ZrCuAl-1.rng" --output=debug.jap_tsukuba_hono_0.nxs 1>stdout.debug.jap_tsukuba_hono_0.txt 2>stderr.debug.jap_tsukuba_hono_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/ErMnO_pole.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/ErMnO.env" --output=debug.nor_trondheim_hatzeglou_0.nxs 1>stdout.debug.nor_trondheim_hatzeglou_0.txt 2>stderr.debug.nor_trondheim_hatzeglou_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/SiGe.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/SiGe.RRNG" --output=debug.nor_trondheim_hatzeglou_1.nxs 1>stdout.debug.nor_trondheim_hatzeglou_1.txt 2>stderr.debug.nor_trondheim_hatzeglou_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5106_01246-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5106_01246-v02.rrng" --output=debug.nor_trondheim_sohail_2.nxs 1>stdout.debug.nor_trondheim_sohail_2.txt 2>stderr.debug.nor_trondheim_sohail_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5106_01263-v05.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5106_01263-v03range file.rrng" --output=debug.nor_trondheim_sohail_3.nxs 1>stdout.debug.nor_trondheim_sohail_3.txt 2>stderr.debug.nor_trondheim_sohail_3.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Autoclave exposed SL CrN-NbN coated Zr cladding_coating-substrate interface (Fig10 - R52_16437).pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Range file for coating-substrate interface (Fig10).rrng" --output=debug.swe_gothenburg_fazi_0.nxs 1>stdout.debug.swe_gothenburg_fazi_0.txt 2>stderr.debug.swe_gothenburg_fazi_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/As-deposited SL CrN-NbN coated Zr cladding_coating-substrate interface (Fig10 - R52_16433).pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Range file for coating-substrate interface (Fig10).rrng" --output=debug.swe_gothenburg_fazi_1.nxs 1>stdout.debug.swe_gothenburg_fazi_1.txt 2>stderr.debug.swe_gothenburg_fazi_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Autoclave exposed NL CrN-NbN coated Zr cladding_coating bulk (Fig8 - R52_16422).pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Range file for CrNNbN coating (Fig8).rrng" --output=debug.swe_gothenburg_fazi_2.nxs 1>stdout.debug.swe_gothenburg_fazi_2.txt 2>stderr.debug.swe_gothenburg_fazi_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/As-deposited NL CrN-NbN coated Zr cladding_coating bulk (Fig8 -R52_16413).pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Range file for CrNNbN coating (Fig8).rrng" --output=debug.swe_gothenburg_fazi_3.nxs 1>stdout.debug.swe_gothenburg_fazi_3.txt 2>stderr.debug.swe_gothenburg_fazi_3.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Autoclave exposed SL CrN-NbN coated Zr cladding_coating bulk (Fig8 -R52_15858).pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Range file for CrNNbN coating (Fig8).rrng" --output=debug.swe_gothenburg_fazi_4.nxs 1>stdout.debug.swe_gothenburg_fazi_4.txt 2>stderr.debug.swe_gothenburg_fazi_4.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/As-deposited SL CrN-NbN coated Zr cladding_coating bulk (Fig8 - R52_15840).pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Range file for CrNNbN coating (Fig8).rrng" --output=debug.swe_gothenburg_fazi_5.nxs 1>stdout.debug.swe_gothenburg_fazi_5.txt 2>stderr.debug.swe_gothenburg_fazi_5.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5038_00333-v02.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/rng_5pj.rrng" --output=debug.usa_denton_smith_0.nxs 1>stdout.debug.usa_denton_smith_0.txt 2>stderr.debug.usa_denton_smith_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5038_00556-v04.epos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/rng_5pj.rrng" --output=debug.usa_denton_smith_1.nxs 1>stdout.debug.usa_denton_smith_1.txt 2>stderr.debug.usa_denton_smith_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Si.apt" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Si.RNG" --output=debug.usa_denton_smith_2.nxs 1>stdout.debug.usa_denton_smith_2.txt 2>stderr.debug.usa_denton_smith_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R13_03871-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/ORNL format CuNi Range File.rng" --output=debug.usa_harvard_barroo_0.nxs 1>stdout.debug.usa_harvard_barroo_0.txt 2>stderr.debug.usa_harvard_barroo_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R13_03871-v01.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/ORNL format CuNi Range File.rng" --output=debug.usa_harvard_barroo_1.nxs 1>stdout.debug.usa_harvard_barroo_1.txt 2>stderr.debug.usa_harvard_barroo_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R94_10497.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R94_10497.rrng" --output=debug.usa_knoxville_levine_0.nxs 1>stdout.debug.usa_knoxville_levine_0.txt 2>stderr.debug.usa_knoxville_levine_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R31_06365-v02.pos" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R31_06365-v02.rrng" --output=debug.usa_portland_wang_0.nxs 1>stdout.debug.usa_portland_wang_0.txt 2>stderr.debug.usa_portland_wang_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R31_11381-v02.ato" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Ceria_11553.rrng" --output=debug.usa_richland_kruska_0.nxs 1>stdout.debug.usa_richland_kruska_0.txt 2>stderr.debug.usa_richland_kruska_0.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R31_11553-v01.ato" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Ceria_11553.rrng" --output=debug.usa_richland_kruska_1.nxs 1>stdout.debug.usa_richland_kruska_1.txt 2>stderr.debug.usa_richland_kruska_1.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R31_11556-v01.ato" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Ceria_11553.rrng" --output=debug.usa_richland_kruska_2.nxs 1>stdout.debug.usa_richland_kruska_2.txt 2>stderr.debug.usa_richland_kruska_2.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R31_11554-v01.ato" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Ceria_11553.rrng" --output=debug.usa_richland_kruska_3.nxs 1>stdout.debug.usa_richland_kruska_3.txt 2>stderr.debug.usa_richland_kruska_3.txt
dataconverter --reader apm --nxdl NXroot --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R31_11378-v01.ato" --input-file="/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Ceria_11553.rrng" --output=debug.usa_richland_kruska_4.nxs 1>stdout.debug.usa_richland_kruska_4.txt 2>stderr.debug.usa_richland_kruska_4.txt
