site_name: Documentation
site_description: |
  The documentation the FAIRmat flavor of the NeXus definitions & pynxtools
site_author: The NOMAD authors
repo_url: https://github.com/FAIRmat-NFDI/pynxtools
edit_uri: ""

nav:
  - Home: index.md
  - Tutorials:
    - tutorial/converting-data-to-nexus.md
    - tutorial/nexus-to-nomad.md
  - How-tos:
    - how-tos/writing-an-appdef.md
    - how-tos/using-multiple-appdefs.md
    - how-tos/transformations.md
    - how-tos/using-pynxtools-test-framework.md
  - Learn:
    - learn/nexus-primer.md
    - learn/nexus-rules.md
    - learn/multiple-appdefs.md
  - Reference:
    - reference/plugins.md
    - reference/definitions.md

plugins:
  - search
  - macros:
      module_name: src/pynxtools/mkdocs

theme:
  name: material
  palette:
    primary: '#2A4CDF'
    accent: '#008A67'
  font:
    text: 'Titillium Web'
  logo: assets/nomad-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - content.code.copy
    - content.code.annotate
  custom_dir: docs/theme

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji
  - mkdocs-click
  - pymdownx.extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  generator: false
  homepage: https://nomad-lab.eu

use_directory_urls: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascript.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js