site_name: FAIRmat NeXus
site_description: |
  The documentation the FAIRmat flavor of the NeXus definitions & pynxtools
site_author: The FAIRmat authors
nav:
  - Home: index.md
  - Tutorials:
    - tutorial/converting-data-to-nexus.md
    - tutorial/nexus-to-nomad.md
  - How-tos:
    - how-tos/using-multiple-appdefs.md
    - how-tos/transformations.md
  - Learn:
    - learn/nexus-primer.md
    - learn/multiple-appdefs.md
  - Reference:
    - reference/definitions.md
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji
  - pymdownx.extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
use_directory_urls: false
plugins:
    - search
    - macros:
        module_name: docs/macros
extra_css:
  - stylesheets/extra.css