#
# Copyright The NOMAD Authors.
#
# This file is part of NOMAD. See https://nomad-lab.eu for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# This file is AUTO-GENERATED from the NeXus definitions (NXDL).
# Run `pynx nomad generate-metainfo --nxdl NXapm` to regenerate.
# Additive-only: the generator will never remove or rename existing members.
# Add normalize() logic directly; it will be preserved on regeneration.
from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np
from nomad.datamodel.metainfo import basesections
from nomad.datamodel.metainfo.basesections import BaseSection
from nomad.metainfo import MEnum, Quantity, Section, SubSection
from nomad.metainfo.data_type import Bytes, Datetime

from pynxtools.nomad.annotations import (
    NeXusAttribute,
    NeXusChoice,
    NeXusDefinition,
    NeXusField,
    NeXusGroup,
    NeXusLink,
)
from pynxtools.nomad.metainfo.base_classes.apm_measurement import ApmMeasurement
from pynxtools.nomad.metainfo.base_classes.cite import Cite
from pynxtools.nomad.metainfo.base_classes.coordinate_system import CoordinateSystem
from pynxtools.nomad.metainfo.base_classes.cs_profiling import CsProfiling
from pynxtools.nomad.metainfo.base_classes.entry import Entry
from pynxtools.nomad.metainfo.base_classes.note import Note
from pynxtools.nomad.metainfo.base_classes.parameters import Parameters
from pynxtools.nomad.metainfo.base_classes.project import Project
from pynxtools.nomad.metainfo.base_classes.roi_process import RoiProcess
from pynxtools.nomad.metainfo.base_classes.sample import Sample
from pynxtools.nomad.metainfo.base_classes.user import User

if TYPE_CHECKING:
    from nomad.datamodel import EntryArchive
    from structlog.stdlib import BoundLogger

__all__ = ["Apm"]


class Apm(Entry):
    """
    Application definition for real or simulated atom probe and field-ion
    microscopy experiments.

    Atom probe tomography and field-ion microscopy are methods for
    characterizing materials through induced controlled extraction of
    individual atoms as ions and molecular ions from a sharp needle-shaped
    specimen.

    Offering isotopic and nanometer-scale resolution, atom probe data enable
    quantification of local chemical composition and computing of volumetric
    reconstructions which are models for the atomic architecture of the small
    specimen volume analyzed. These reconstructions provide input for
    characterization of atomic segregation at crystal defects. The term
    microstructural features is considered as a narrow synonym for crystal
    defects.

    The aim of the NXapm application definition is to provide a general yet
    specific enough solution to serialize artifacts for virtually all atom
    probe and field-ion microscopy experiments.

    Before summarizing the design of the base classes and the parts of the
    NXapm application definition, it is worthwhile to recall and distinguish
    concepts that are related to atom extraction events and the molecular ions
    that are frequently generated by the sequence of events:

    * An atom probe instrument uses laser or voltage pulsing events to trigger
    ion extraction events. * These ions are accelerated in an electric field
    towards a position-sensitive detector system. Physical events and
    corresponding signal on this detector is triggered by an ion hitting the
    detector. Some of these events are not necessarily caused by or directly
    correlated with an identifiable pulsing event. * Note that only a part the
    specimen volume can be measured and finite detection efficiency means that
    not all atoms in the measured volume will be detected. Neutral atoms can
    escape detection. Some ions escape detection because they hit into walls of
    the analysis_chamber.

    Raw data are typically processed as follows:

    * Detector pulses and their timing are processed and discriminated into
    signal events of different quality levels. High quality events might be
    considered in further processing to identify the corresponding molecular
    ion and its original position in the reconstructed volume. * Signal
    calibration and filtering steps are applied to convert raw time-of-flight
    data to calibrated mass-to-charge state ratio values and obtain calibrated
    impact positions on the detector. * Ranging and identifying an ion that
    corresponds to each detector event. Isotopic abundance and theoretical
    models inform these ranging algorithms. * Finally, such selected ion impact
    positions and iontypes are used to compute a reconstructed volume of the
    specimen using backprojection algorithms. In effect, an atom probe
    measurement is a combination of a data acquisition and a data analysis
    workflow.

    Not only in AMETEK/Cameca's APSuite/IVAS software, which the majority of
    atom probers use, these concepts are well distinguished. However, the
    algorithms used to transform correlations between pulses and physical
    events into actual events, the so-called detector hits of ions, is a
    proprietary one. This algorithm is also referred to as the hit finding
    algorithm.

    Due to this practical inaccessibility of details, virtually all atom probe
    studies currently use a reporting schema where the course of the specimen
    evaporation is documented such that quantities are a function of
    evaporation_id i.e. actual event/ion, i.e. after having the hit finding
    algorithm and correlations applied. That is the evaporation_id values take
    the role of an implicit time and course of the experiment given that ion
    extraction physically is a sequential process.

    This application definition includes fields that the atom probe community
    has decided to represent best practices for reporting atom probe
    measurements. Exemplar mapping tables are provided for documents that
    reported these best practices to translate technical term into concepts of
    the NXapm application definition.

    *The NeXus application definition NXapm defines a hierarchical data model
    with ten building blocks:*

    The data model represents a tree of concepts. The tree is constructed from
    groups of concepts representing the branches, together with fields and
    attributes representing leaves. NXapm is defined by composing and
    specializing base classes into the following ten categories:

    - The field ``definition`` specifies that the data schema is NXapm. In
    combination with administrative metadata such as the attribute
    ``NeXus_version`` provided by :ref:`NXroot` this specifies which version of
    NXapm the instance data in a NeXus/HDF5 file are compliant with. - The
    fields ``run_number``, ``experiment_alias``, ``experiment_description`` and
    the group ``userID`` provide concepts for storing organizational metadata
    that contextualize the work within the research workflow and humans
    involved in this. - The fields ``start_time``, ``end_time`` provide
    concepts for framing a temporal context for the research. - The groups
    ``citeID``, ``noteID`` provide concepts for adding contextual details such
    as citations or notes that are associated with the data, i.e. other
    artifacts that are deemed relevant when reporting about a measurement or
    simulation. These groups are useful when NXapm is used as a serialization
    format for technology-partner-agnostic archival of data and metadata that
    have been collected during a session with an atom probe instrument. The
    terms run and session are understood as exact synonyms that refer to an
    uninterrupted period of measurement. Resuming measurement on a specimen
    after an interruption is viewed as a new run and the new data should not be
    appended to the previous run, but written to either a new NXentry, or a new
    file. Removing the specimen from the instrument is an interruption.
    Changing evaporation conditions while the specimen is remains in the
    analysis_chamber and resuming thereafter the measurement is not considered
    as an interruption. It is a common strategy to probe the evaporation
    process for different instrument parameters. Each individual collection
    should then though be stored in an own NXapm_event_data group. Parking the
    specimen to the buffer_chamber and resuming the measurement at a later
    stage is an interruption. During a run, the microscope is used for a
    certain amount of time to characterize a single specimen. - The groups
    ``sample`` and ``specimen`` provide concepts for storing metadata about the
    sample and the specimen, i.e. the smaller part that was removed from the
    sample to be measured in the atom probe session. The term "tip" in the
    context of atom probe research is considered jargon. Specimen is an exact
    synonym for tip. - The field ``operation_mode`` and group ``measurement``
    provides concepts that are useful for describing a measurement during a
    session with an atom probe or field-ion microscope. This includes the chain
    of events of data and metadata that were collected during such a session. -
    The group ``simulation`` provides concepts that are useful for describing a
    simulation of an atom extraction, ionization, and ion trajectory
    simulation. Combined with ``measurement`` this provides a data schema for
    defining a digital twin of the instrument and its setup. - The groups
    ``consistent_rotations``, and ``NAMED_reference_frame`` provide concepts
    for reporting coordinate systems (frames of reference) and rotation
    conventions that clarify how data should be interpreted specifying the
    rotation of orientable objects in the microscope, its components, or of
    crystals and crystal defects in the material analyzed. - The group
    ``atom_probeID`` provides concepts for the computational workflows that
    were used to convert raw detector data into reconstructed ion positions and
    documentation of ranging definitions made. - The group ``profiling``
    provides concepts for reporting computational details such as programs and
    libraries used, for documenting the libraries of virtual environments such
    as those used by conda or python virtual environment, including details
    about the computing hardware used, and documenting capabilities for
    performance analyses and benchmarking of the software or its parts.

    *Design choices:*

    Given that most atom probe instruments across the globe were built by
    AMETEK/Cameca and are delivered with the AP Suite/IVAS software there is
    some homogeneity in how a measurement is performed and which data artifacts
    and algorithms used for data processing. Complementary use of open-source
    software specifically for the reconstruction, ranging, and later data
    processing stages contributes to a landscape of multiple tools in use.
    Therefore, communication of atom probe research differs between user
    groups. This holds even more so true for the sub community in atom probe
    which study physical mechanisms involved during ionization to the point
    that here that almost each research work defines different simulation tools
    with different types of data artifacts.

    NXapm defines constraints on the existence and cardinality of concepts and
    its concept branches but seeks to offer a compromise. The key design
    pattern followed is that most branches are made optional or at most
    recommended but their child concepts are conditionally required. Thereby,
    NXapm can cover a variety of simple but also complex use cases. An example
    of this parent-optional-but-children-stronger-restricted design is the
    combination of the optional group ``measurement`` with its required child
    ``measurement/instrument``: Users which report simulations are not forced
    to document the instrument but users which have characterized a specimen
    are motivated to report about the instrument. They are though not
    necessarily required to report all the details of the instruments'
    components because the design pattern is applied recursively.

    *NXapm distinguishes and stores instance data based on how long they remain
    unchanged:*

    ``measurement`` provides two groups ``measurement/instrument`` and
    ``measurement/eventID``. The first group is designed for storing metadata
    about the instrument that do not change over the course of the session.
    Examples are the name of the technology partner who built the microscope or
    whether a laser or voltage pulser and reflectron exists or not. The second
    group is designed for metadata and data that are collected during the
    session with the instrument. These, are stored as instances of
    ``measurement/eventID``, events that can be time-stamped individually. Each
    instance of a group ``measurement/eventID`` contains
    ``measurement/instrument`` whose purpose is to store those specific state
    and settings of the instrument that was present during the collection of
    the event. Thereby, changing conditions such as campaigns with different
    target detection rate can be stored.

    Noteworthy, such an approach of the atom probe detecting groups of events
    and storing these as groups has also been in use in the proprietary
    software via CamecaRoot, a set of customized data structures and file
    formats that use the CernRoot library. By virtue of design this reduces
    unnecessary repetition of metadata stored in the first group.

    ``atom_probeID`` offer classes for the each task relevant task in the data
    processing pipeline that converts raw detector event data to calibrated
    mass-to-charge-state-ratio values and hit_position on the detector. These
    include ``initial_specimen``, and ``final_specimen`` locations for storing
    images of the specimen prior/after the measurement as considered best
    practice by AMETEK/Cameca, ``raw_data`` for delay-line timing data,
    ``hit_finding`` for details of the hit finding algorithm,
    ``hit_spatial_filtering`` a process that filters hits of too low quality
    and those laying outside the about to be computed reconstruction volume.
    Furthermore, group ``voltage_and_bowl`` offers a place for documenting
    calibrations and processing nonlinearities. Group
    ``mass_to_charge_conversion`` is used to document the mass calibration and
    the conversion from time-of-flight to mass-to-charge-state-ratio values.

    Finally, the groups ``reconstruction`` and ``ranging`` were designed to
    match and document the classical approaches how from all the previous
    sources of input one can compute a reconstructed volume, and apply peak
    fitting routines on the mass-to-charge-state-ratio histogram to label ions,
    i.e. range them for their isotopic identity. Group
    ``atom_probeID/reconstruction/naive_discretization`` offers a standardized
    way to report simple three-dimensional histograms. Group
    ``atom_probeID/ranging/peak_identification/ionID`` and its complementing
    group
    ``atom_probeID/ranging/peak_identification/ionID/charge_state_analysis``
    solves the issue that the ranging definitions in classical file formats are
    not reported for always for their isotopic identity and charge state. The
    field ``atom_probeID/ranging/peak_identification/iontypes`` provides a
    place for storing a compact representation of the results of each ranging
    definition made at the level of each ion.

    *The compatibility of NXapm and NXem:**

    The design of NXapm mirrors that of :ref:`NXem`. This was an intentional
    choice to support the increasingly stronger connection between these two
    materials characterization methods, especially in light of recent advances
    in the direct coupling of atom probe and transmission electron microscopes
    and scanning transmission electron microscopes.
    """

    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm"
        ],
        a_nexus_definition=NeXusDefinition(
            nx_class="NXapm",
            category="application",
            symbols={
                "n_ht": "Number of hit qualities, the so-called hit types, distinguished.",
                "n_dld": "Number of delay-line-detector (DLD) wires of the detector.",
                "n_bins": "Number of bins used in the mass-to-charge-state-ratio spectrum.",
                "p": "Number of pulses collected in between start_time and end_time resolved by an\n                instance of :ref:`NXapm_event_data`. If this is not defined, p is the number of\n                ions included in the reconstructed volume if the application definition is used\n                to store results of an already reconstructed dataset.",
                "p_out": "Number of pulses returned by the hit_finding algorithm.\n                Neither necessarily equal to p nor to n.",
                "n": "Number of ions spatially filtered from results of the hit_finding algorithm\n                from which an instance of a reconstructed volume has been generated.\n                These ions get new identifier assigned in the process, the so-called\n                evaporation_id. This identifier must not be confused with the pulse_id.\n                This value is typically smaller than both p and p_out.",
                "m_r": "Number of mass resolution values.",
            },
        ),
    )

    profiling = SubSection(
        section_def="pynxtools.nomad.metainfo.applications.apm.ApmProfiling",
        repeats=False,
        description=(
            "The configuration of the software that was used to generate this "
            "NeXus file."
        ),
    )
    citeID = SubSection(
        section_def="pynxtools.nomad.metainfo.applications.apm.ApmCiteID",
        repeats=True,
        variable=True,
    )
    noteID = SubSection(
        section_def="pynxtools.nomad.metainfo.applications.apm.ApmNoteID",
        repeats=True,
        variable=True,
    )
    project = SubSection(
        section_def="pynxtools.nomad.metainfo.applications.apm.ApmProject",
        repeats=False,
    )
    userID = SubSection(
        section_def="pynxtools.nomad.metainfo.applications.apm.ApmUserID",
        repeats=True,
        variable=True,
    )
    sample = SubSection(
        section_def="pynxtools.nomad.metainfo.applications.apm.ApmSample",
        repeats=False,
        description=(
            "Description of the sample from which the specimen was prepared or "
            "site-specifically cut out using e.g. a focused-ion beam instrument. "
            "In NXapm, a measurement is performed on a specimen. Since APM "
            "specimens are very small, they are typically cut from a larger "
            "object with some scientific significance, which NXapm refers to as "
            "a sample."
        ),
    )
    specimen = SubSection(
        section_def="pynxtools.nomad.metainfo.applications.apm.ApmSpecimen",
        repeats=False,
        description=(
            "Description of the specimen that was cut off from the sample. In "
            "atom probe jargon this is typically referred to as the tip."
        ),
    )
    consistent_rotations = SubSection(
        section_def="pynxtools.nomad.metainfo.applications.apm.ApmConsistentRotations",
        repeats=False,
        description=(
            "The conventions used when reporting crystal orientations. We follow "
            "the best practices of the Material Science community that are "
            "defined in reference "
            "`<https://doi.org/10.1088/0965-0393/23/8/083501>`_."
        ),
    )
    NAMED_reference_frameID = SubSection(
        section_def="pynxtools.nomad.metainfo.applications.apm.ApmNAMED_reference_frameID",
        repeats=True,
        variable=True,
        description=(
            "A coordinate system. Multiple instances require unique names. "
            "Several Euclidean coordinate systems (CS) are used in the field of "
            "atom probe: * World space; a CS specifying a local coordinate "
            "system of the planet earth which identifies into which direction "
            "gravity is pointing such that the laboratory space CS can be "
            "rotated into this world CS. * The laboratory space; a CS specifying "
            "the room where the instrument is located in or a physical landmark "
            "on the instrument, e.g. the direction of the transfer rod where "
            "positive is the direction how the rod has to be pushed during "
            "loading a specimen into the instrument. In summary, this CS is "
            "defined by the chassis of the instrument. Suggested name of the "
            "group ``laboratory_reference_frame``. * The specimen space; a CS "
            "affixed to either the base or the initial apex of the specimen, "
            "whose z axis points towards the detector. Suggested name of the "
            "group ``specimen_reference_frame``. * The detector space; a CS "
            "affixed to the detector plane whose xy plane is usually in the "
            "detector and whose z axis points towards the specimen. This is a "
            "distorted space with respect to the reconstructed ion positions. "
            "Suggested name of the group ``detector_reference_frame``. * The "
            "reconstruction space; a CS in which the reconstructed ion positions "
            "are defined. The orientation depends on the analysis software used. "
            "* Eventually further coordinate systems attached to the flight path "
            "of individual ions might be defined. Suggested name of the group "
            "``reconstruction_reference_frame``. To achieve unique names, the "
            'prefix "NAMED" should be replaced to with something derived from '
            'an alias for the coordinate system, or the value of the "alias" '
            "field. Use the suffix _reference_frame when creating specific "
            "instances of NXcoordinate_system e.g. laboratory_reference_frame, "
            "reconstruction_reference_frame and so on and so forth. In atom "
            "probe microscopy a frequently used choice for the detector space "
            "(CS) is discussed with the so-called detector space image stack. "
            "This is a stack of two-dimensional histograms of detected ions "
            "within a predefined evaporation identifier interval. Typically, the "
            "set of ion evaporation sequence identifiers is grouped into chunks. "
            "For each chunk a histogram of the ion hit positions on the detector "
            "is computed. This leaves the possibility for inconsistency between "
            "the so-called detector space and the e.g. specimen space. To avoid "
            "these ambiguities, instances of :ref:`NXtransformations` should be "
            "used."
        ),
    )
    measurement = SubSection(
        section_def="pynxtools.nomad.metainfo.applications.apm.ApmApmMeasurement",
        repeats=False,
    )
    simulation = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.apm_simulation.ApmSimulation",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXapm_simulation",
            name="simulation",
            name_type="specified",
            optionality="optional",
        ),
    )
    atom_probeID = SubSection(
        section_def="pynxtools.nomad.metainfo.applications.apm.ApmAtom_probeID",
        repeats=True,
        variable=True,
        description=(
            "A region-of-interest analyzed either during or after the session "
            "for which specific processed data of the measured or simulated data "
            "are available. If a single instance is required the group should be "
            "named atom_probe. If multiple groups are required these should be "
            "named atom_probe1, atom_probe2, and so on and so forth."
        ),
    )

    definition = Quantity(
        type=MEnum(["NXapm"]),
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-definition-field"
        ],
        a_nexus_field=NeXusField(
            name="definition",
            type="NX_CHAR",
            name_type="specified",
            optionality="required",
            enumeration=["NXapm"],
        ),
    )
    definition__version = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-definition-version-attribute"
        ],
        a_nexus_attribute=NeXusAttribute(
            name="version",
            type="NX_CHAR",
            name_type="specified",
            optionality="optional",
            parent_field="definition",
        ),
    )
    run_number = Quantity(
        type=np.int64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-run-number-field"
        ],
        dimensionality="dimensionless",
        description=(
            "The identifier whereby the experiment is referred to in the control "
            "software. It is common practice in atom probe research to refer to "
            "a measurement on a single specimen as a run. When working with "
            "AMETEK/Cameca instruments it is a common practice also to store all "
            "data associated with such a run in files whose name is composed "
            "from a prefix that details the type of instrument (e.g. R5076) "
            "followed by the run_number. These filenames are often used as the "
            "specimen_name or experiment_identifier. The terms run and session "
            "are understood as exact synonyms. For other instruments, such as "
            "the one from Stuttgart or Oxcart from Erlangen, or the instruments "
            "at GPM in Rouen, use the identifier which matches best conceptually "
            "to the LEAP run number. The field does not have to be required, if "
            "the information is recoverable in the dataset which for LEAP "
            "instruments is the case; provided these RHIT or HITS files "
            "respectively are stored alongside a data artifact. With NXapm the "
            "RHIT or HITS can be stored via NXnote in the hit_finding algorithm "
            "section. As a destructive microscopy technique, a run can be "
            "performed only once. It is possible, however, to interrupt a run "
            "and restart data acquisition while still using the same specimen. "
            "In this case, each evaporation run needs to be distinguished with "
            "different run numbers. We follow this habit of most atom probe "
            "groups. Such interrupted runs should be stored as individual "
            ":ref:`NXentry` instances in one NeXus file."
        ),
        a_nexus_field=NeXusField(
            name="run_number",
            type="NX_UINT",
            name_type="specified",
            optionality="recommended",
            units="NX_UNITLESS",
        ),
    )
    experiment_alias = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-experiment-alias-field"
        ],
        description=(
            "Alias or short name which scientists can use to refer to this experiment."
        ),
        a_nexus_field=NeXusField(
            name="experiment_alias",
            type="NX_CHAR",
            name_type="specified",
            optionality="optional",
        ),
    )
    experiment_description = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-experiment-description-field"
        ],
        description=(
            "Free-text description about the experiment. Users are strongly "
            "advised to parameterize the description of their experiment by "
            "using respective groups and fields and base classes instead of "
            "writing prose into the field."
        ),
        a_nexus_field=NeXusField(
            name="experiment_description",
            type="NX_CHAR",
            name_type="specified",
            optionality="optional",
        ),
    )
    start_time = Quantity(
        type=Datetime,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-start-time-field"
        ],
        description=(
            "ISO 8601 time code with local time zone offset to UTC information "
            "included when the atom probe session started. If the exact duration "
            "of the measurement is not relevant, start_time only should be used. "
            "The start_time is required in order to ensure that at least one "
            "point in time is provided for full temporal context to a "
            "measurement and simulation when writing instance data using NXapm. "
            "Otherwise, the instance data can not be sorted in order or even "
            "placed in a logical sequence to other steps of the research "
            "workflow, which would disallow using functionalities in research "
            "data management systems that rely on temporal context. Specifying "
            "start_time and end_time is useful for capturing more detailed "
            "bookkeeping of the experiment. The user should be aware that even "
            "with having both dates specified, it may not be possible to infer "
            "how long the experiment took or for how long data were collected. "
            "More detailed timing data over the course of the experiment have to "
            "be collected to compute this event chain during the experiment. For "
            "this purpose the :ref:`NXapm_event_data` instance should be used."
        ),
        a_nexus_field=NeXusField(
            name="start_time",
            type="NX_DATE_TIME",
            name_type="specified",
            optionality="required",
        ),
    )
    end_time = Quantity(
        type=Datetime,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-end-time-field"
        ],
        description=(
            "ISO 8601 time code with local time zone offset to UTC included when "
            "the atom probe session ended. Writing the end_time can be a tricky "
            "in practice. If written at the start of the experiment, it can only "
            "be an estimate. If written at the end, there is the risk for having "
            "the computer crash or lose power. The absence of end_time should "
            "not be interpreted as that the experiment was aborted. Only, the "
            "field ``status`` should be used for communicating such abortion."
        ),
        a_nexus_field=NeXusField(
            name="end_time",
            type="NX_DATE_TIME",
            name_type="specified",
            optionality="recommended",
        ),
    )
    elapsed_time = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-elapsed-time-field"
        ],
        dimensionality="[time]",
        description=(
            "How long did the measurement take e.g. use "
            "CRunHeader.CAnalysis.fElapsedTime"
        ),
        a_nexus_field=NeXusField(
            name="elapsed_time",
            type="NX_FLOAT",
            name_type="specified",
            optionality="recommended",
            units="NX_TIME",
        ),
    )
    operation_mode = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-operation-mode-field"
        ],
        description=(
            "What type of atom probe experiment is performed to inform research "
            "data management systems and allow filtering: * apt are experiments "
            "where the analysis_chamber has no imaging gas. Experiments with "
            "LEAP instruments are typically with this operation_mode. * fim are "
            "experiments where the analysis_chamber has an imaging gas, which "
            "should be specified with the atmosphere in the analysis_chamber "
            "group. * apt_fim should be used for combinations of the two imaging "
            "modes. Few experiments of this type have been performed, as it can "
            "be detrimental to LEAP systems (see `S. Katnagallu et al. "
            "<https://doi.org/10.1017/S1431927621012381>`_)."
        ),
        a_nexus_field=NeXusField(
            name="operation_mode",
            type="NX_CHAR",
            name_type="specified",
            optionality="required",
            enumeration=["apt", "fim", "apt_fim"],
            open_enum=True,
        ),
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)


# =============================================================================
# Named concept groups — only when the group element defines own quantities that
# differ from the generic class (changed optionality, extra fields, different
# type/units/enumeration). These inherit from the specific generic class so all
# base quantities are available.
# Resolved lazily by NOMAD at __init_metainfo__() time via string FQNs.
# =============================================================================


class ApmProfiling(CsProfiling):
    """
    The configuration of the software that was used to generate this NeXus
    file.
    """

    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-profiling-group"
        ],
        a_nexus_group=NeXusGroup(
            nx_class="NXcs_profiling",
            name="profiling",
            name_type="specified",
            optionality="optional",
        ),
    )

    programID = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.program.Program",
        repeats=True,
        variable=True,
        a_nexus_group=NeXusGroup(
            nx_class="NXprogram",
            name="programID",
            name_type="partial",
            optionality="optional",
            min_occurs=0,
        ),
    )
    environment = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.collection.Collection",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXcollection",
            name="environment",
            name_type="specified",
            optionality="recommended",
        ),
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)


class ApmCiteID(Cite):
    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-citeid-group"
        ],
        variable=True,
        a_nexus_group=NeXusGroup(
            nx_class="NXcite",
            name="citeID",
            name_type="partial",
            optionality="optional",
            min_occurs=0,
        ),
    )

    author = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-citeid-author-field"
        ],
        description=("The author(s) of that reference."),
        a_nexus_field=NeXusField(
            name="author",
            type="NX_CHAR",
            name_type="specified",
            optionality="optional",
        ),
    )
    doi = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-citeid-doi-field"
        ],
        a_nexus_field=NeXusField(
            name="doi",
            type="NX_CHAR",
            name_type="specified",
            optionality="required",
        ),
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)


class ApmNoteID(Note):
    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-noteid-group"
        ],
        variable=True,
        a_nexus_group=NeXusGroup(
            nx_class="NXnote",
            name="noteID",
            name_type="partial",
            optionality="optional",
            min_occurs=0,
        ),
    )

    type = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-noteid-type-field"
        ],
        a_nexus_field=NeXusField(
            name="type",
            type="NX_CHAR",
            name_type="specified",
            optionality="recommended",
        ),
    )
    file_name = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-noteid-file-name-field"
        ],
        a_nexus_field=NeXusField(
            name="file_name",
            type="NX_CHAR",
            name_type="specified",
            optionality="required",
        ),
    )
    checksum = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-noteid-checksum-field"
        ],
        a_nexus_field=NeXusField(
            name="checksum",
            type="NX_CHAR",
            name_type="specified",
            optionality="recommended",
        ),
    )
    algorithm = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-noteid-algorithm-field"
        ],
        a_nexus_field=NeXusField(
            name="algorithm",
            type="NX_CHAR",
            name_type="specified",
            optionality="recommended",
        ),
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)


class ApmProject(Project):
    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-project-group"
        ],
        a_nexus_group=NeXusGroup(
            nx_class="NXproject",
            name="project",
            name_type="specified",
            optionality="optional",
        ),
    )

    name_quantity = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-project-name-field"
        ],
        a_nexus_field=NeXusField(
            name="name",
            type="NX_CHAR",
            name_type="specified",
            optionality="required",
        ),
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)


class ApmUserID(User):
    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-userid-group"
        ],
        variable=True,
        a_nexus_group=NeXusGroup(
            nx_class="NXuser",
            name="userID",
            name_type="partial",
            optionality="recommended",
        ),
    )

    identifierNAME = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-userid-identifiername-field"
        ],
        variable=True,
        a_nexus_field=NeXusField(
            name="identifierNAME",
            type="NX_CHAR",
            name_type="partial",
            optionality="recommended",
        ),
    )
    identifierNAME__type = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-userid-identifiername-type-attribute"
        ],
        a_nexus_attribute=NeXusAttribute(
            name="type",
            type="NX_CHAR",
            name_type="specified",
            optionality="required",
            parent_field="identifierNAME",
            enumeration=[
                "ARK",
                "DOI",
                "Hdl",
                "IGSN",
                "ISNI",
                "ISSN",
                "ISSN-L",
                "ORCID",
                "PURL",
                "ROR",
                "URL",
                "URN",
            ],
            open_enum=True,
        ),
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)


class ApmSample(Sample):
    """
    Description of the sample from which the specimen was prepared or
    site-specifically cut out using e.g. a focused-ion beam instrument.

    In NXapm, a measurement is performed on a specimen. Since APM specimens are
    very small, they are typically cut from a larger object with some
    scientific significance, which NXapm refers to as a sample.
    """

    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-sample-group"
        ],
        a_nexus_group=NeXusGroup(
            nx_class="NXsample",
            name="sample",
            name_type="specified",
            optionality="recommended",
        ),
    )

    chemical_composition = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.chemical_composition.ChemicalComposition",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXchemical_composition",
            name="chemical_composition",
            name_type="specified",
            optionality="recommended",
        ),
    )

    identifierNAME = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-sample-identifiername-field"
        ],
        variable=True,
        a_nexus_field=NeXusField(
            name="identifierNAME",
            type="NX_CHAR",
            name_type="partial",
            optionality="recommended",
        ),
    )
    is_simulation = Quantity(
        type=bool,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-sample-is-simulation-field"
        ],
        description=(
            "False, if the sample is a real one. True, if the sample is a virtual one."
        ),
        a_nexus_field=NeXusField(
            name="is_simulation",
            type="NX_BOOLEAN",
            name_type="specified",
            optionality="required",
        ),
    )
    alias = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-sample-alias-field"
        ],
        description=("Given name/alias for the sample."),
        a_nexus_field=NeXusField(
            name="alias",
            type="NX_CHAR",
            name_type="specified",
            optionality="required",
        ),
    )
    grain_diameter = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-sample-grain-diameter-field"
        ],
        dimensionality="[length]",
        description=(
            "Qualitative information about the grain size, here specifically "
            "described as the equivalent spherical diameter of an assumed "
            "average grain size for the crystal ensemble. If the specimen does "
            "not contain many crystals average values might be an unreliable "
            "descriptor. Reporting a grain size may be useful though as it "
            "allows judging if specific features are expected to be found in the "
            "detector hit map."
        ),
        a_nexus_field=NeXusField(
            name="grain_diameter",
            type="NX_FLOAT",
            name_type="specified",
            optionality="optional",
            units="NX_LENGTH",
        ),
    )
    grain_diameter_errors = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-sample-grain-diameter-errors-field"
        ],
        dimensionality="[length]",
        description=("Magnitude of the standard deviation of the grain_diameter."),
        a_nexus_field=NeXusField(
            name="grain_diameter_errors",
            type="NX_FLOAT",
            name_type="specified",
            optionality="optional",
            units="NX_LENGTH",
        ),
    )
    heat_treatment_time = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-sample-heat-treatment-time-field"
        ],
        dimensionality="[time]",
        description=(
            "An array of elapsed time, the independent axis, of a "
            "time-temperature curve. This field can be used in combination with "
            "heat_treatment_temperature and heat_treatment_temperature_errors as "
            "well as heat_treatment_quenching_rate and "
            "heat_treatment_quenching_rate_errors respectively. In this case, "
            "these fields should also be stored as an array with the same "
            "dimensions as heat_treatment_time to store the dependant axes of a "
            "time-temperature curve as well as its first derivative."
        ),
        a_nexus_field=NeXusField(
            name="heat_treatment_time",
            type="NX_FLOAT",
            name_type="specified",
            optionality="optional",
            units="NX_TIME",
        ),
    )
    heat_treatment_temperature = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-sample-heat-treatment-temperature-field"
        ],
        dimensionality="[temperature]",
        description=(
            "If heat_treatment_time is absent, the temperature of the last heat "
            "treatment step before quenching. Knowledge about this value can "
            "give an idea how the sample was heat treated. However, if a "
            "documentation of the annealing treatment as a function of time is "
            "available one should better rely on this information and have it "
            "stored alongside the NeXus file. If heat_treatment_time is "
            "provided, the temperature. Consult the docstring of "
            "heat_treatment_time."
        ),
        a_nexus_field=NeXusField(
            name="heat_treatment_temperature",
            type="NX_FLOAT",
            name_type="specified",
            optionality="optional",
            units="NX_TEMPERATURE",
        ),
    )
    heat_treatment_temperature_errors = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-sample-heat-treatment-temperature-errors-field"
        ],
        dimensionality="[temperature]",
        description=(
            "Magnitude of the standard deviation of the "
            "heat_treatment_temperature. If heat_treatment_time is provided, the "
            "magnitude of the standard derivation of the temperature. Consult "
            "the docstring of heat_treatment_time."
        ),
        a_nexus_field=NeXusField(
            name="heat_treatment_temperature_errors",
            type="NX_FLOAT",
            name_type="specified",
            optionality="optional",
            units="NX_TEMPERATURE",
        ),
    )
    heat_treatment_quenching_rate = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-sample-heat-treatment-quenching-rate-field"
        ],
        description=(
            "If heat_treatment_time is absent, the rate of the last quenching "
            "step. Knowledge about this value can give an idea how the sample "
            "was heat treated. However, there are many situations where one can "
            "imagine that the scalar value for just the quenching rate is "
            "insufficient. If heat_treatment_time is provided, the first "
            "derivative of the time-temperature curve. Consult the docstring of "
            "heat_treatment_time for further details."
        ),
        a_nexus_field=NeXusField(
            name="heat_treatment_quenching_rate",
            type="NX_FLOAT",
            name_type="specified",
            optionality="optional",
            units="NX_ANY",
        ),
    )
    heat_treatment_quenching_rate_errors = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-sample-heat-treatment-quenching-rate-errors-field"
        ],
        description=(
            "Magnitude of the standard deviation of the "
            "heat_treatment_quenching_rate. If heat_treatment_time is provided, "
            "the magnitude of the standard deviation of the first derivative of "
            "the time-temperature curve. Consult the docstring of "
            "heat_treatment_time for further details."
        ),
        a_nexus_field=NeXusField(
            name="heat_treatment_quenching_rate_errors",
            type="NX_FLOAT",
            name_type="specified",
            optionality="optional",
            units="NX_ANY",
        ),
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)


class ApmSpecimen(Sample):
    """
    Description of the specimen that was cut off from the sample.

    In atom probe jargon this is typically referred to as the tip.
    """

    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-specimen-group"
        ],
        a_nexus_group=NeXusGroup(
            nx_class="NXsample",
            name="specimen",
            name_type="specified",
            optionality="required",
        ),
    )

    identifierNAME = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-specimen-identifiername-field"
        ],
        variable=True,
        a_nexus_field=NeXusField(
            name="identifierNAME",
            type="NX_CHAR",
            name_type="partial",
            optionality="recommended",
        ),
    )
    is_simulation = Quantity(
        type=bool,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-specimen-is-simulation-field"
        ],
        description=(
            "False, if the specimen is a real one. True, if the specimen is a "
            "virtual one."
        ),
        a_nexus_field=NeXusField(
            name="is_simulation",
            type="NX_BOOLEAN",
            name_type="specified",
            optionality="required",
        ),
    )
    alias = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-specimen-alias-field"
        ],
        description=(
            "Given name or an alias. Better use identifierNAME and "
            "identifier_parent instead. A single NXentry should be used only for "
            "the characterization of a single specimen."
        ),
        a_nexus_field=NeXusField(
            name="alias",
            type="NX_CHAR",
            name_type="specified",
            optionality="recommended",
        ),
    )
    identifier_parent = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-specimen-identifier-parent-field"
        ],
        description=(
            "Identifier of the sample from which the specimen was cut or the "
            'string "n/a". The purpose of this field is to support '
            "functionalities for tracking sample provenance via a research data "
            "management system."
        ),
        a_nexus_field=NeXusField(
            name="identifier_parent",
            type="NX_CHAR",
            name_type="specified",
            optionality="recommended",
        ),
    )
    preparation_date = Quantity(
        type=Datetime,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-specimen-preparation-date-field"
        ],
        description=(
            "ISO 8601 time code with local time zone offset to UTC information "
            "when the specimen was prepared. Ideally, report the end of the "
            "preparation, i.e. the last known time the measured specimen surface "
            "was actively prepared. Ideally, this matches the last timestamp "
            "that is mentioned in the digital resource pointed to by "
            "identifier_parent. Knowing when the specimen was exposed to e.g. "
            "specific atmosphere is especially required for environmentally "
            "sensitive material such as hydrogen charged specimens or "
            "experiments including tracers with a short half time."
        ),
        a_nexus_field=NeXusField(
            name="preparation_date",
            type="NX_DATE_TIME",
            name_type="specified",
            optionality="recommended",
        ),
    )
    atom_types = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-specimen-atom-types-field"
        ],
        description=(
            "List of comma-separated elements from the IUPAC periodic table that "
            "are contained in the specimen. If the specimen substance has "
            "multiple components, all elements from each component must be "
            "included in `atom_types`. The purpose of the field is to offer "
            "research data management systems an opportunity to parse the "
            "relevant elements without having to interpret these from the "
            "resources pointed to by identifier_parent or walk through "
            "eventually deeply nested groups in data instances."
        ),
        a_nexus_field=NeXusField(
            name="atom_types",
            type="NX_CHAR",
            name_type="specified",
            optionality="required",
        ),
    )
    is_polycrystalline = Quantity(
        type=bool,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-specimen-is-polycrystalline-field"
        ],
        description=(
            "True, if the specimen contains a grain or phase boundary. False, if "
            "the specimen is a single crystal."
        ),
        a_nexus_field=NeXusField(
            name="is_polycrystalline",
            type="NX_BOOLEAN",
            name_type="specified",
            optionality="recommended",
        ),
    )
    is_amorphous = Quantity(
        type=bool,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-specimen-is-amorphous-field"
        ],
        description=(
            "True, if the specimen is amorphous. False, if the specimen is not."
        ),
        a_nexus_field=NeXusField(
            name="is_amorphous",
            type="NX_BOOLEAN",
            name_type="specified",
            optionality="recommended",
        ),
    )
    initial_radius = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-specimen-initial-radius-field"
        ],
        dimensionality="[length]",
        description=(
            "Ideally measured otherwise best elaborated guess of the initial "
            "radius of the specimen."
        ),
        a_nexus_field=NeXusField(
            name="initial_radius",
            type="NX_FLOAT",
            name_type="specified",
            optionality="recommended",
            units="NX_LENGTH",
        ),
    )
    shank_angle = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-specimen-shank-angle-field"
        ],
        dimensionality="[angle]",
        description=(
            "Ideally measured, otherwise best estimate, of the initial shank "
            "angle. This is a measure of the specimen taper. Define it in such a "
            "way that the base of the specimen is modelled as a conical frustrum "
            "so that the shank angle is the smallest angle between the specimen "
            "space z-axis and a vector on the lateral surface of the cone."
        ),
        a_nexus_field=NeXusField(
            name="shank_angle",
            type="NX_FLOAT",
            name_type="specified",
            optionality="recommended",
            units="NX_ANGLE",
        ),
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)


class ApmConsistentRotations(Parameters):
    """
    The conventions used when reporting crystal orientations. We follow the
    best practices of the Material Science community that are defined in
    reference `<https://doi.org/10.1088/0965-0393/23/8/083501>`_.
    """

    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-consistent-rotations-group"
        ],
        a_nexus_group=NeXusGroup(
            nx_class="NXparameters",
            name="consistent_rotations",
            name_type="specified",
            optionality="recommended",
        ),
    )

    rotation_handedness = Quantity(
        type=MEnum(["counter_clockwise", "clockwise"]),
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-consistent-rotations-rotation-handedness-field"
        ],
        description=(
            "Convention how a positive rotation angle is defined when viewing "
            "from the end of the rotation unit vector towards its origin. This "
            "is in accordance with convention 2 of reference "
            "`<https://doi.org/10.1088/0965-0393/23/8/083501>`_. "
            "Counter_clockwise is equivalent to a right-handed choice. Clockwise "
            "is equivalent to a left-handed choice."
        ),
        a_nexus_field=NeXusField(
            name="rotation_handedness",
            type="NX_CHAR",
            name_type="specified",
            optionality="required",
            enumeration=["counter_clockwise", "clockwise"],
        ),
    )
    rotation_convention = Quantity(
        type=MEnum(["passive", "active"]),
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-consistent-rotations-rotation-convention-field"
        ],
        description=(
            "How are rotations interpreted into an orientation according to "
            "convention 3 of reference "
            "`<https://doi.org/10.1088/0965-0393/23/8/083501>`_."
        ),
        a_nexus_field=NeXusField(
            name="rotation_convention",
            type="NX_CHAR",
            name_type="specified",
            optionality="required",
            enumeration=["passive", "active"],
        ),
    )
    euler_angle_convention = Quantity(
        type=MEnum(
            [
                "zxz",
                "xyx",
                "yzy",
                "zyz",
                "xzx",
                "yxy",
                "xyz",
                "yzx",
                "zxy",
                "xzy",
                "zyx",
                "yxz",
            ]
        ),
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-consistent-rotations-euler-angle-convention-field"
        ],
        description=(
            "How are Euler angles interpreted given that there are several "
            "choices e.g. zxz, xyz according to convention 4 of reference "
            "`<https://doi.org/10.1088/0965-0393/23/8/083501>`_. The most "
            "frequently used convention in Materials Science is zxz, which is "
            "based on the work of H.-J. Bunge but using other conventions is "
            "possible. Proper Euler angles are distinguished from Tait-Bryan "
            "angles."
        ),
        a_nexus_field=NeXusField(
            name="euler_angle_convention",
            type="NX_CHAR",
            name_type="specified",
            optionality="required",
            enumeration=[
                "zxz",
                "xyx",
                "yzy",
                "zyz",
                "xzx",
                "yxy",
                "xyz",
                "yzx",
                "zxy",
                "xzy",
                "zyx",
                "yxz",
            ],
        ),
    )
    axis_angle_convention = Quantity(
        type=MEnum(["rotation_angle_on_interval_zero_to_pi"]),
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-consistent-rotations-axis-angle-convention-field"
        ],
        description=(
            "To which angular range is the rotation angle argument of an "
            "axis-angle pair parameterization constrained according to "
            "convention 5 of reference "
            "`<https://doi.org/10.1088/0965-0393/23/8/083501>`_."
        ),
        a_nexus_field=NeXusField(
            name="axis_angle_convention",
            type="NX_CHAR",
            name_type="specified",
            optionality="required",
            enumeration=["rotation_angle_on_interval_zero_to_pi"],
        ),
    )
    sign_convention = Quantity(
        type=MEnum(["p_plus_one", "p_minus_one"]),
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-consistent-rotations-sign-convention-field"
        ],
        description=(
            "Which sign convention is followed when converting orientations "
            "between different parametrizations/representations according to "
            "convention 6 of reference "
            "`<https://doi.org/10.1088/0965-0393/23/8/083501>`_."
        ),
        a_nexus_field=NeXusField(
            name="sign_convention",
            type="NX_CHAR",
            name_type="specified",
            optionality="required",
            enumeration=["p_plus_one", "p_minus_one"],
        ),
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)


class ApmNAMED_reference_frameID(CoordinateSystem):
    """
    A coordinate system. Multiple instances require unique names.

    Several Euclidean coordinate systems (CS) are used in the field of atom
    probe:

    * World space; a CS specifying a local coordinate system of the planet
    earth which identifies into which direction gravity is pointing such that
    the laboratory space CS can be rotated into this world CS. * The laboratory
    space; a CS specifying the room where the instrument is located in or a
    physical landmark on the instrument, e.g. the direction of the transfer rod
    where positive is the direction how the rod has to be pushed during loading
    a specimen into the instrument. In summary, this CS is defined by the
    chassis of the instrument. Suggested name of the group
    ``laboratory_reference_frame``. * The specimen space; a CS affixed to
    either the base or the initial apex of the specimen, whose z axis points
    towards the detector. Suggested name of the group
    ``specimen_reference_frame``. * The detector space; a CS affixed to the
    detector plane whose xy plane is usually in the detector and whose z axis
    points towards the specimen. This is a distorted space with respect to the
    reconstructed ion positions. Suggested name of the group
    ``detector_reference_frame``. * The reconstruction space; a CS in which the
    reconstructed ion positions are defined. The orientation depends on the
    analysis software used. * Eventually further coordinate systems attached to
    the flight path of individual ions might be defined. Suggested name of the
    group ``reconstruction_reference_frame``.

    To achieve unique names, the prefix "NAMED" should be replaced to with
    something derived from an alias for the coordinate system, or the value of
    the "alias" field.

    Use the suffix _reference_frame when creating specific instances of
    NXcoordinate_system e.g. laboratory_reference_frame,
    reconstruction_reference_frame and so on and so forth.

    In atom probe microscopy a frequently used choice for the detector space
    (CS) is discussed with the so-called detector space image stack. This is a
    stack of two-dimensional histograms of detected ions within a predefined
    evaporation identifier interval. Typically, the set of ion evaporation
    sequence identifiers is grouped into chunks.

    For each chunk a histogram of the ion hit positions on the detector is
    computed. This leaves the possibility for inconsistency between the
    so-called detector space and the e.g. specimen space.

    To avoid these ambiguities, instances of :ref:`NXtransformations` should be
    used.
    """

    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-named-reference-frameid-group"
        ],
        variable=True,
        a_nexus_group=NeXusGroup(
            nx_class="NXcoordinate_system",
            name="NAMED_reference_frameID",
            name_type="partial",
            optionality="required",
            min_occurs=1,
        ),
    )

    alias = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-named-reference-frameid-alias-field"
        ],
        a_nexus_field=NeXusField(
            name="alias",
            type="NX_CHAR",
            name_type="specified",
            optionality="optional",
        ),
    )
    type = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-named-reference-frameid-type-field"
        ],
        a_nexus_field=NeXusField(
            name="type",
            type="NX_CHAR",
            name_type="specified",
            optionality="required",
            enumeration=["undefined", "cartesian"],
            open_enum=True,
        ),
    )
    origin = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-named-reference-frameid-origin-field"
        ],
        a_nexus_field=NeXusField(
            name="origin",
            type="NX_CHAR",
            name_type="specified",
            optionality="recommended",
        ),
    )
    x = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-named-reference-frameid-x-field"
        ],
        dimensionality="[length]",
        shape=[3],
        a_nexus_field=NeXusField(
            name="x",
            type="NX_NUMBER",
            name_type="specified",
            optionality="required",
            units="NX_LENGTH",
        ),
    )
    x_direction = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-named-reference-frameid-x-direction-field"
        ],
        a_nexus_field=NeXusField(
            name="x_direction",
            type="NX_CHAR",
            name_type="specified",
            optionality="recommended",
        ),
    )
    y = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-named-reference-frameid-y-field"
        ],
        dimensionality="[length]",
        shape=[3],
        a_nexus_field=NeXusField(
            name="y",
            type="NX_NUMBER",
            name_type="specified",
            optionality="required",
            units="NX_LENGTH",
        ),
    )
    y_direction = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-named-reference-frameid-y-direction-field"
        ],
        a_nexus_field=NeXusField(
            name="y_direction",
            type="NX_CHAR",
            name_type="specified",
            optionality="recommended",
        ),
    )
    z = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-named-reference-frameid-z-field"
        ],
        dimensionality="[length]",
        shape=[3],
        a_nexus_field=NeXusField(
            name="z",
            type="NX_NUMBER",
            name_type="specified",
            optionality="required",
            units="NX_LENGTH",
        ),
    )
    z_direction = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-named-reference-frameid-z-direction-field"
        ],
        a_nexus_field=NeXusField(
            name="z_direction",
            type="NX_CHAR",
            name_type="specified",
            optionality="recommended",
        ),
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)


class ApmApmMeasurement(ApmMeasurement):
    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-measurement-group"
        ],
        a_nexus_group=NeXusGroup(
            nx_class="NXapm_measurement",
            name="measurement",
            name_type="specified",
            optionality="optional",
        ),
    )

    standing_voltage_time = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="standing_voltage_time",
            name_type="specified",
            optionality="optional",
        ),
    )
    pulse_frequency_time = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="pulse_frequency_time",
            name_type="specified",
            optionality="optional",
        ),
    )
    detection_rate_time = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="detection_rate_time",
            name_type="specified",
            optionality="optional",
        ),
    )
    detection_rate_set_time = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="detection_rate_set_time",
            name_type="specified",
            optionality="optional",
        ),
    )
    pressure_time = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="pressure_time",
            name_type="specified",
            optionality="optional",
        ),
    )
    specimen_voltage_time = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="specimen_voltage_time",
            name_type="specified",
            optionality="optional",
        ),
    )
    specimen_temperature_time = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="specimen_temperature_time",
            name_type="specified",
            optionality="optional",
        ),
    )
    ambient_temperature_time = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="ambient_temperature_time",
            name_type="specified",
            optionality="optional",
        ),
    )
    reflectron_voltage_time = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="reflectron_voltage_time",
            name_type="specified",
            optionality="optional",
        ),
    )
    xstage_position_time = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="xstage_position_time",
            name_type="specified",
            optionality="optional",
        ),
    )
    ystage_position_time = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="ystage_position_time",
            name_type="specified",
            optionality="optional",
        ),
    )
    zstage_position_time = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="zstage_position_time",
            name_type="specified",
            optionality="optional",
        ),
    )
    standing_voltage_sequence = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="standing_voltage_sequence",
            name_type="specified",
            optionality="optional",
        ),
    )
    pulse_frequency_sequence = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="pulse_frequency_sequence",
            name_type="specified",
            optionality="optional",
        ),
    )
    detection_rate_sequence = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="detection_rate_sequence",
            name_type="specified",
            optionality="optional",
        ),
    )
    detection_rate_set_sequence = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="detection_rate_set_sequence",
            name_type="specified",
            optionality="optional",
        ),
    )
    pressure_sequence = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="pressure_sequence",
            name_type="specified",
            optionality="optional",
        ),
    )
    specimen_voltage_sequence = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="specimen_voltage_sequence",
            name_type="specified",
            optionality="optional",
        ),
    )
    specimen_temperature_sequence = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="specimen_temperature_sequence",
            name_type="specified",
            optionality="optional",
        ),
    )
    ambient_temperature_sequence = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="ambient_temperature_sequence",
            name_type="specified",
            optionality="optional",
        ),
    )
    reflectron_voltage_sequence = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="reflectron_voltage_sequence",
            name_type="specified",
            optionality="optional",
        ),
    )
    xstage_position_sequence = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="xstage_position_sequence",
            name_type="specified",
            optionality="optional",
        ),
    )
    ystage_position_sequence = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="ystage_position_sequence",
            name_type="specified",
            optionality="optional",
        ),
    )
    zstage_position_sequence = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.data.Data",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXdata",
            name="zstage_position_sequence",
            name_type="specified",
            optionality="optional",
        ),
    )

    status = Quantity(
        type=MEnum(["success", "aborted"]),
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-measurement-status-field"
        ],
        a_nexus_field=NeXusField(
            name="status",
            type="NX_CHAR",
            name_type="specified",
            optionality="recommended",
            enumeration=["success", "aborted"],
        ),
    )
    quality = Quantity(
        type=str,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-measurement-quality-field"
        ],
        a_nexus_field=NeXusField(
            name="quality",
            type="NX_CHAR",
            name_type="specified",
            optionality="recommended",
        ),
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)


class ApmAtom_probeID(RoiProcess):
    """
    A region-of-interest analyzed either during or after the session for which
    specific processed data of the measured or simulated data are available.

    If a single instance is required the group should be named atom_probe. If
    multiple groups are required these should be named atom_probe1,
    atom_probe2, and so on and so forth.
    """

    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/applications/NXapm.html#nxapm-entry-atom-probeid-group"
        ],
        variable=True,
        a_nexus_group=NeXusGroup(
            nx_class="NXroi_process",
            name="atom_probeID",
            name_type="partial",
            optionality="optional",
            min_occurs=0,
        ),
    )

    initial_specimen = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.image.Image",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXimage",
            name="initial_specimen",
            name_type="specified",
            optionality="recommended",
        ),
    )
    final_specimen = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.image.Image",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXimage",
            name="final_specimen",
            name_type="specified",
            optionality="recommended",
        ),
    )
    reconstruction = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.apm_reconstruction.ApmReconstruction",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXapm_reconstruction",
            name="reconstruction",
            name_type="specified",
            optionality="recommended",
        ),
    )
    ranging = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.apm_ranging.ApmRanging",
        repeats=False,
        a_nexus_group=NeXusGroup(
            nx_class="NXapm_ranging",
            name="ranging",
            name_type="specified",
            optionality="recommended",
        ),
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)
