#
# Copyright The NOMAD Authors.
#
# This file is part of NOMAD. See https://nomad-lab.eu for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""(Sub-)parser mapping concepts and content from *.nxs.mtex files on NXem."""

"""
README.md
*.nxs.mtex is a specific HDF5-based data processing report format for users of
the MTex/Matlab texture toolbox to export results from MTex to other software.

The format uses several concepts from the NXem appdef.
Instances of *.nxs.mtex files thus contain several but not necessarily
all pieces of information which the NXem application definition demands
as required.

Therefore, pynxtools can be used to append these missing pieces of information.

Currently implemented I/O support for this format:
The current implementation of *.nxs.mtex sub-parser in the em reader
is implemented such that an existent *.nxs.mtex file is copied and
this copy annotated with the missing pieces of information.

The nxs_mtex sub-parser is the only sub-parser of the em parser
with this copying-the-input-file design. For all other file formats
the em parser uses the template to instantiate the complete file
including all numerical data eventually generated by one or several
of the sub-parsers.
"""


class NxEmNxsMTexSubParser():
    """Map content from *.nxs.mtex files on an instance of NXem.

    """
    def __init__(self):
        pass

    def parse(self, template: dict, entry_id: int = 1) -> dict:
        """Pass because for *.nxs.mtex all data are already in the copy of the output."""
        return template
