#
# Copyright The NOMAD Authors.
#
# This file is part of NOMAD. See https://nomad-lab.eu for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# This file is AUTO-GENERATED from the NeXus definitions (NXDL).
# Run `pynx nomad generate-metainfo --nxdl NXphase_lock_loop` to regenerate.
# Additive-only: the generator will never remove or rename existing members.
# Add normalize() logic directly; it will be preserved on regeneration.
#
# NOTE: This class is generated from a community-contributed NXDL definition.
# The NXDL source may change across versions. Regenerate after updating definitions.
from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np
from nomad.datamodel.metainfo.annotations import (
    ELNAnnotation,
    ELNComponentEnum,
    SchemaAnnotation,
)
from nomad.metainfo import MEnum, Quantity, Section, SubSection
from nomad.metainfo.data_type import Bytes, Datetime

from pynxtools.nomad.annotations import (
    NeXusAttribute,
    NeXusChoice,
    NeXusDefinition,
    NeXusField,
    NeXusGroup,
    NeXusLink,
)
from pynxtools.nomad.metainfo.base_classes.component import Component
from pynxtools.nomad.metainfo.base_classes.fabrication import Fabrication

if TYPE_CHECKING:
    from nomad.datamodel import EntryArchive
    from structlog.stdlib import BoundLogger

__all__ = ["PhaseLockLoop"]


class PhaseLockLoop(Component):
    """
    A base class definition for a phase-locked loop (PLL) used in AFM
    experiments.

    The PLL has three main components: 1. Phase-detector 2. Loop-filter 3.
    Voltage-controlled oscillator (VCO)

    Depending on the phase error from the phase detector due to the phase
    difference between the Reference and output from the VCO signals, the PLL
    adjusts the output frequency to minimize the phase error.

    Measuring the phase error, the PLL can be in one of three states: - Zero
    phase error: The output signal is in coherence with the reference signal
    (lock condition). - Constant phase error: The output signal has a constant
    phase difference from the reference signal, and therefore, both reference
    signals have the same frequency (lock condition). - Continuous increasing
    phase error: The output signal's phase continuously changes therefore they
    have different frequencies, indicating the PLL is in an unlock condition.
    """

    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop"
        ],
        a_nexus_definition=NeXusDefinition(
            nx_class="NXphase_lock_loop",
            category="base",
        ),
    )

    hardware = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.phase_lock_loop.PhaseLockLoopHardware",
        repeats=False,
        description=("Manufacturer and model of the PLL hardware or controller."),
    )
    calibration = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.calibration.Calibration",
        repeats=False,
        description=(
            "Calibration information for the PLL, including any relevant "
            "parameters or procedures."
        ),
        a_nexus_group=NeXusGroup(
            nx_class="NXcalibration",
            name="calibration",
            name_type="specified",
            optionality="optional",
        ),
    )
    phase_detector = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.phase_lock_loop.PhaseLockLoopPhaseDetector",
        repeats=False,
        description=(
            "The phase detector component of the PLL, which compares the phase "
            "between the reference signal generated (e.g., in AFM, generated by "
            "the cantilever) and the signal coming from the VCO."
        ),
    )
    loop_filter = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.phase_lock_loop.PhaseLockLoopLoopFilter",
        repeats=False,
        description=(
            "The loop filter component of the PLL filters the voltage from the "
            "phase detector to the VCO. It extracts the average voltage of the "
            "phase error signals emitted from the phase detector."
        ),
    )
    voltage_controlled_oscillator = SubSection(
        section_def="pynxtools.nomad.metainfo.base_classes.phase_lock_loop.PhaseLockLoopVoltageControlledOscillator",
        repeats=False,
        description=(
            "The voltage-controlled oscillator (VCO) component of the PLL, which "
            "generates the output signal based on the filtered voltage from the "
            "loop filter."
        ),
    )

    center_frequency = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-center-frequency-field"
        ],
        dimensionality="1 / [time]",
        unit="hertz",
        description=(
            "The center frequency of the PLL is the middle frequency of the "
            "PLL's operating range."
        ),
        a_nexus_field=NeXusField(
            name="center_frequency",
            type="NX_NUMBER",
            name_type="specified",
            optionality="optional",
            units="NX_FREQUENCY",
        ),
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.NumberEditQuantity,
        ),
        a_display={"unit": "hertz"},
    )
    frequency_bandwidth = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-frequency-bandwidth-field"
        ],
        dimensionality="1 / [time]",
        unit="hertz",
        description=(
            "The frequency bandwidth of the PLL is where it responds or is "
            "stable. If phase difference (also called phase error) is calculated "
            "from the input and output signal frequencies."
        ),
        a_nexus_field=NeXusField(
            name="frequency_bandwidth",
            type="NX_NUMBER",
            name_type="specified",
            optionality="optional",
            units="NX_FREQUENCY",
        ),
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.NumberEditQuantity,
        ),
        a_display={"unit": "hertz"},
    )
    phase_bandwidth = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-phase-bandwidth-field"
        ],
        dimensionality="1 / [time]",
        unit="hertz",
        description=(
            "The phase bandwidth of the PLL is where it responds or is stable. "
            "If phase difference (also called phase error) is calculated from "
            "the input and output signal phases."
        ),
        a_nexus_field=NeXusField(
            name="phase_bandwidth",
            type="NX_NUMBER",
            name_type="specified",
            optionality="optional",
            units="NX_FREQUENCY",
        ),
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.NumberEditQuantity,
        ),
        a_display={"unit": "hertz"},
    )
    frequency_step = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-frequency-step-field"
        ],
        dimensionality="1 / [time]",
        unit="hertz",
        description=(
            "The frequency step size of the PLL determines the resolution of "
            "frequency changes."
        ),
        a_nexus_field=NeXusField(
            name="frequency_step",
            type="NX_NUMBER",
            name_type="specified",
            optionality="optional",
            units="NX_FREQUENCY",
        ),
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.NumberEditQuantity,
        ),
        a_display={"unit": "hertz"},
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)


# =============================================================================
# Named concept groups — only when the group element defines own quantities that
# differ from the generic class (changed optionality, extra fields, different
# type/units/enumeration). These inherit from the specific generic class so all
# base quantities are available.
# Resolved lazily by NOMAD at __init_metainfo__() time via string FQNs.
# =============================================================================


class PhaseLockLoopHardware(Fabrication):
    """
    Manufacturer and model of the PLL hardware or controller.
    """

    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-hardware-group"
        ],
        a_nexus_group=NeXusGroup(
            nx_class="NXfabrication",
            name="hardware",
            name_type="specified",
            optionality="optional",
        ),
    )

    type = Quantity(
        type=MEnum(["type-1", "type-2", "type-3"]),
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-hardware-type-field"
        ],
        description=(
            "Types (design parameter for circuit) of the PLL from type-1, "
            "type-2, and type-3 available in device specifications (for "
            "mathematical details: "
            "https://www.nxp.com/docs/en/application-note/AN535.pdf). Type is "
            "defined by the number of poles that exist in the transfer function "
            "of the PLL."
        ),
        a_nexus_field=NeXusField(
            name="type",
            type="NX_CHAR",
            name_type="specified",
            optionality="optional",
            enumeration=["type-1", "type-2", "type-3"],
        ),
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.EnumEditQuantity,
        ),
    )
    order = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-hardware-order-field"
        ],
        dimensionality="dimensionless",
        unit="dimensionless",
        description=(
            "Order of the PLL. This is characteristic of circuit design and is "
            "defined as the number of roots of characteristics polynomial of the "
            "PLL circuit."
        ),
        a_nexus_field=NeXusField(
            name="order",
            type="NX_NUMBER",
            name_type="specified",
            optionality="optional",
            units="NX_UNITLESS",
        ),
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.NumberEditQuantity,
        ),
        a_display={"unit": "dimensionless"},
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)


class PhaseLockLoopPhaseDetector(Component):
    """
    The phase detector component of the PLL, which compares the phase between
    the reference signal generated (e.g., in AFM, generated by the cantilever)
    and the signal coming from the VCO.
    """

    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-phase-detector-group"
        ],
        a_nexus_group=NeXusGroup(
            nx_class="NXcomponent",
            name="phase_detector",
            name_type="specified",
            optionality="optional",
        ),
    )

    reference_frequency = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-phase-detector-reference-frequency-field"
        ],
        dimensionality="1 / [time]",
        unit="hertz",
        description=(
            "The input reference frequency to the PLL through the component "
            "Phase-detector."
        ),
        a_nexus_field=NeXusField(
            name="reference_frequency",
            type="NX_NUMBER",
            name_type="specified",
            optionality="optional",
            units="NX_FREQUENCY",
        ),
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.NumberEditQuantity,
        ),
        a_display={"unit": "hertz"},
    )
    frequency_shift = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-phase-detector-frequency-shift-field"
        ],
        dimensionality="1 / [time]",
        unit="hertz",
        description=(
            "Measured or target shift in oscillation from the VCO. relative to "
            "the reference signal."
        ),
        a_nexus_field=NeXusField(
            name="frequency_shift",
            type="NX_NUMBER",
            name_type="specified",
            optionality="optional",
            units="NX_FREQUENCY",
        ),
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.NumberEditQuantity,
        ),
        a_display={"unit": "hertz"},
    )
    reference_phase = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-phase-detector-reference-phase-field"
        ],
        dimensionality="[angle]",
        unit="radian",
        description=("Reference phase of the input signal to the phase detector."),
        a_nexus_field=NeXusField(
            name="reference_phase",
            type="NX_NUMBER",
            name_type="specified",
            optionality="optional",
            units="NX_ANGLE",
        ),
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.NumberEditQuantity,
        ),
        a_display={"unit": "radian"},
    )
    phase_error = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-phase-detector-phase-error-field"
        ],
        dimensionality="[angle]",
        unit="radian",
        description=(
            "Measured phase error (also called phase difference) between the "
            "reference signal and the VCO output."
        ),
        a_nexus_field=NeXusField(
            name="phase_error",
            type="NX_NUMBER",
            name_type="specified",
            optionality="optional",
            units="NX_ANGLE",
        ),
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.NumberEditQuantity,
        ),
        a_display={"unit": "radian"},
    )
    Kp_coefficient = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-phase-detector-kp-coefficient-field"
        ],
        dimensionality="[mass] * [length] ** 2 / [time] ** 3 / [current] / [angle]",
        unit="V/rad",
        description=(
            "The gain coefficient of the phase detector which determines how "
            "much the output voltage changes in response to a phase difference "
            "(V/rad)."
        ),
        a_nexus_field=NeXusField(
            name="Kp_coefficient",
            type="NX_NUMBER",
            name_type="specified",
            optionality="optional",
            units="V/rad",
        ),
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.NumberEditQuantity,
        ),
        a_display={"unit": "V/rad"},
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)


class PhaseLockLoopLoopFilter(Component):
    """
    The loop filter component of the PLL filters the voltage from the phase
    detector to the VCO. It extracts the average voltage of the phase error
    signals emitted from the phase detector.
    """

    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-loop-filter-group"
        ],
        a_nexus_group=NeXusGroup(
            nx_class="NXcomponent",
            name="loop_filter",
            name_type="specified",
            optionality="optional",
        ),
    )

    Kf_coefficient = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-loop-filter-kf-coefficient-field"
        ],
        dimensionality="dimensionless",
        unit="dimensionless",
        description=(
            "The Kf coefficient, called loop filter gain, determines the gain of "
            "the loop filter circuit in the PLL."
        ),
        a_nexus_field=NeXusField(
            name="Kf_coefficient",
            type="NX_NUMBER",
            name_type="specified",
            optionality="optional",
            units="NX_UNITLESS",
        ),
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.NumberEditQuantity,
        ),
        a_display={"unit": "dimensionless"},
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)


class PhaseLockLoopVoltageControlledOscillator(Component):
    """
    The voltage-controlled oscillator (VCO) component of the PLL, which
    generates the output signal based on the filtered voltage from the loop
    filter.
    """

    m_def = Section(
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-voltage-controlled-oscillator-group"
        ],
        a_nexus_group=NeXusGroup(
            nx_class="NXcomponent",
            name="voltage_controlled_oscillator",
            name_type="specified",
            optionality="optional",
        ),
    )

    output_frequency_range = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-voltage-controlled-oscillator-output-frequency-range-field"
        ],
        dimensionality="1 / [time]",
        unit="hertz",
        description=(
            "The output frequency range (written in an array of frequencies as "
            "[min, max]) of the VCO which is the range of frequencies it can "
            "generate. The range is either the same as the frequency bandwidth "
            "of the PLL or shorter and inside that."
        ),
        a_nexus_field=NeXusField(
            name="output_frequency_range",
            type="NX_NUMBER",
            name_type="specified",
            optionality="optional",
            units="NX_FREQUENCY",
        ),
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.NumberEditQuantity,
        ),
        a_display={"unit": "hertz"},
    )
    Kn_coefficient = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-voltage-controlled-oscillator-kn-coefficient-field"
        ],
        dimensionality="dimensionless",
        unit="dimensionless",
        description=(
            "The Kn coefficient, called the input-output frequency ratio, "
            "relates the input frequency to the output frequency of the VCO. "
            "This coefficient is used to adjust the output frequency based on "
            "the input frequency."
        ),
        a_nexus_field=NeXusField(
            name="Kn_coefficient",
            type="NX_NUMBER",
            name_type="specified",
            optionality="optional",
            units="NX_UNITLESS",
        ),
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.NumberEditQuantity,
        ),
        a_display={"unit": "dimensionless"},
    )
    Ko_coefficient = Quantity(
        type=np.float64,
        links=[
            "https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXphase_lock_loop.html#nxphase_lock_loop-voltage-controlled-oscillator-ko-coefficient-field"
        ],
        description=(
            "The output voltage coefficient of the VCO, which determines how "
            "much the output frequency changes in response to a change in input "
            "voltage (Hz/V)."
        ),
        a_nexus_field=NeXusField(
            name="Ko_coefficient",
            type="NX_NUMBER",
            name_type="specified",
            optionality="optional",
            units="NX_ANY",
        ),
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.NumberEditQuantity,
        ),
    )

    def normalize(self, archive: EntryArchive, logger: BoundLogger) -> None:
        super().normalize(archive, logger)
