name: build_and_deploy_mkdocs

on:
  push:
    branches:
      - master  # Triggers deployment on push to the main branch

env:
  UV_SYSTEM_PYTHON: true

permissions:
   contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache mkdocs-material environment
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install Dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install --no-cache-dir ".[docs]"  # Install without cache to ensure latest version

      - name: Check dataconverter Installation
        run: |
          dataconverter --help

      - name: Build and Deploy
        run: |
          mkdocs gh-deploy --force --remote-branch gh-pages