name: build_and_deploy_mkdocs

on:
  push:
    branches:
      - master  # Triggers deployment on push to the master branch

permissions:
   contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv and set the python version to 3.11
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.11

      - name: Cache mkdocs-material environment
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install Dependencies
        run: |
          uv pip install --no-cache-dir ".[docs]"

      - name: Build and Deploy
        run: |
          mkdocs gh-deploy --force --remote-branch gh-pages