name: validate NOMAD dependencies compatibility

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate_nomad_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout pynxtools
      uses: actions/checkout@v2

    - name: Checkout NOMAD from GitLab
      run: |
        git clone https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR.git nomad
        cd nomad
        git checkout develop 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # or any other version you need

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Compile pyproject.toml to requirements.txt
      run: |
        # Use pip-compile to generate requirements.txt from pyproject.toml
        pip-compile pyproject.toml --output-file=pyproject-requirements.txt
        
    - name: Combine and Check Dependencies
      run: |
        # Combine NOMADS requirements with pynxtools dependencies from pyproject.toml
        cat nomad/requirements-dev.txt > combined-requirements.txt
        echo "" >> combined-requirements.txt
        cat pyproject-requirements.txt >> combined-requirements.txt

        # Install the combined dependencies
        pip install -r combined-requirements.txt
      env:
        PYTHONPATH: ""  # Ensure no pre-installed packages interfere with the test