name: Spell Check

on:
  pull_request:
    branches:
      - master  # Triggers deployment on push to the master branch

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies and dictionary
      run: |
        npm install -g cspell jq @cspell/dict-scientific-terms-us

    - name: Run cspell
      run: |
        cspell --config cspell.json "docs/**/*.md" "CITATION.cff" "README.md"

    - name: Fail on errors
      run: |
        if [[ $? -ne 0 ]]; then
          echo "There are spelling errors in your code. Please fix them and try again."
          exit 1
        fi
