# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test xps plugin

on:
  push:
    branches: [appdef-graph-tests]
  pull_request:
    branches: [master]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install coverage coveralls
      - name: Install package
        run: |
          pip install ".[dev]"
      # Test for XPS Plugin
      - name: clone XPS repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: FAIRmat-NFDI/pynxtools-xps
          path: pynxtools-xps
      - name: Run XPS tests
        run: |
          cd pynxtools-xps
          git checkout fix-nxs-validation
          pip install .
          pytest tests/.